// mobile_app/src/screens/ConnectingScreen.tsx
// Ported from frontend/src/lib/screens/ConnectingScreen.svelte. Pure
// cosmetic screen — three pulsing rings + a 400ms dot-cycle, then
// onConnected() fires after a flat 3s, same as the source (no backend call
// happens here itself).
import { useEffect, useRef, useState } from "react";
import { View, Text, Animated, Easing } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { Wifi, CheckCircle2 } from "lucide-react-native";
import UnganaLogoMark from "@/components/UnganaLogoMark";

const STEPS = ["Payment verified", "Allocating session", "Connecting to network"];
const RINGS = [1, 0.6, 0.35];

function PulseRing({ baseSize, opacity, duration }: { baseSize: number; opacity: number; duration: number }) {
  const progress = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const loop = Animated.loop(
      Animated.timing(progress, { toValue: 1, duration: duration * 1000, easing: Easing.out(Easing.ease), useNativeDriver: true })
    );
    loop.start();
    return () => loop.stop();
  }, [progress, duration]);

  const scale = progress.interpolate({ inputRange: [0, 1], outputRange: [0.8, 1.3] });
  const ringOpacity = progress.interpolate({ inputRange: [0, 1], outputRange: [opacity, 0] });

  return (
    <Animated.View
      pointerEvents="none"
      style={{
        position: "absolute",
        width: baseSize,
        height: baseSize,
        borderRadius: baseSize / 2,
        borderWidth: 2,
        borderColor: "#C45C38",
        opacity: ringOpacity,
        transform: [{ scale }],
      }}
    />
  );
}

export default function ConnectingScreen({ onConnected }: { onConnected: () => void | Promise<void> }) {
  const [dots, setDots] = useState(0);

  useEffect(() => {
    const d = setInterval(() => setDots((prev) => (prev + 1) % 4), 400);
    const t = setTimeout(() => {
      onConnected();
    }, 3000);
    return () => {
      clearInterval(d);
      clearTimeout(t);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <LinearGradient colors={["#1D3C2A", "#2E5A3E"]} style={{ flex: 1 }}>
      <View className="flex-1 items-center justify-center px-8">
        <View className="items-center" style={{ gap: 24 }}>
          <View className="items-center justify-center" style={{ width: 140, height: 140 }}>
            {RINGS.map((o, i) => (
              <PulseRing key={i} baseSize={60 + i * 36} opacity={o} duration={1.2 + i * 0.3} />
            ))}
            <View
              className="w-16 h-16 rounded-full items-center justify-center"
              style={{ backgroundColor: "rgba(196,92,56,0.30)", borderWidth: 2, borderColor: "#C45C38" }}
            >
              <Wifi size={28} color="#C45C38" />
            </View>
          </View>

          <UnganaLogoMark height={36} />

          <View className="items-center">
            <Text className="text-xl font-serif" style={{ color: "#E8D4B0" }}>
              Connecting you{".".repeat(dots)}
            </Text>
            <Text className="text-sm mt-2" style={{ color: "#C4DAC0" }}>
              Setting up your internet session
            </Text>
          </View>

          <View className="w-full" style={{ gap: 8 }}>
            {STEPS.map((step, i) => (
              <View key={step} className="flex-row items-center gap-3">
                <View
                  className="w-5 h-5 rounded-full items-center justify-center"
                  style={{ backgroundColor: i < 2 ? "rgba(196,92,56,0.25)" : "rgba(255,255,255,0.18)" }}
                >
                  {i < 2 ? <CheckCircle2 size={12} color="#C45C38" /> : <View className="w-2 h-2 rounded-full" style={{ backgroundColor: "#C4DAC0" }} />}
                </View>
                <Text className="text-xs" style={{ color: i < 2 ? "#C4DAC0" : "#96B496" }}>
                  {step}
                </Text>
              </View>
            ))}
          </View>
        </View>
      </View>
    </LinearGradient>
  );
}

// frontend/src/lib/screens/ConnectingScreen.svelte
<script>
  import { Wifi, CheckCircle2 } from '@lucide/svelte';
  import UnganaLogoMark from '$lib/components/UnganaLogoMark.svelte';

  let { onConnected } = $props();

  let dots = $state(0);

  $effect(() => {
    const d = setInterval(() => (dots = (dots + 1) % 4), 400);
    const t = setTimeout(onConnected, 3000);
    return () => {
      clearInterval(d);
      clearTimeout(t);
    };
  });

  const steps = ['Payment verified', 'Allocating session', 'Connecting to network'];
</script>

<div
  class="flex flex-col items-center justify-center px-8"
  style="min-height: 100dvh; background: linear-gradient(160deg, #1D3C2A 0%, #2E5A3E 100%);"
>
  <div class="flex flex-col items-center gap-6">
    <!-- Pulsing rings -->
    <div class="relative flex items-center justify-center" style="width: 140px; height: 140px;">
      {#each [1, 0.6, 0.35] as o, i (i)}
        <div
          class="absolute rounded-full border-2 border-[#C45C38]"
          style="width: {60 + i * 36}px; height: {60 + i * 36}px; opacity: {o}; animation: ping-ring {1.2 + i * 0.3}s ease-out infinite;"
        ></div>
      {/each}
      <div
        class="w-16 h-16 rounded-full flex items-center justify-center z-10"
        style="background: rgba(196,92,56,0.30); border: 2px solid #C45C38;"
      >
        <Wifi size={28} color="#C45C38" />
      </div>
    </div>

    <UnganaLogoMark height={36} />

    <div class="text-center">
      <p class="text-xl font-bold text-[#E8D4B0]" style="font-family: 'Playfair Display', serif;">
        Connecting you{'.'.repeat(dots)}
      </p>
      <p class="text-sm text-[#C4DAC0] mt-2">Setting up your internet session</p>
    </div>

    <div class="flex flex-col gap-2 w-full">
      {#each steps as step, i (step)}
        <div class="flex items-center gap-3">
          <div
            class="w-5 h-5 rounded-full flex items-center justify-center shrink-0"
            style="background: {i < 2 ? 'rgba(196,92,56,0.25)' : 'rgba(255,255,255,0.18)'};"
          >
            {#if i < 2}
              <CheckCircle2 size={12} color="#C45C38" />
            {:else}
              <div class="w-2 h-2 rounded-full bg-[#C4DAC0] animate-pulse"></div>
            {/if}
          </div>
          <span class="text-xs" style="color: {i < 2 ? '#C4DAC0' : '#96B496'};">{step}</span>
        </div>
      {/each}
    </div>
  </div>
</div>
