// mobile_app/src/screens/WarningScreen.tsx
// Ported from frontend/src/lib/screens/WarningScreen.svelte.
import { useEffect, useState } from "react";
import { View, Text, Pressable } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { AlertTriangle, WifiOff, Clock, RotateCcw, type LucideIcon } from "lucide-react-native";
import DemoBadge from "@/components/DemoBadge";
import { formatTime, type Package } from "@/lib/data";

const ROWS: { icon: LucideIcon; text: string }[] = [
  { icon: WifiOff, text: "Internet access will stop" },
  { icon: Clock, text: "Your session will be archived" },
  { icon: RotateCcw, text: "You can buy a new session anytime" },
];

export default function WarningScreen({
  pkg: _pkg,
  remaining,
  mode = "simulation",
  onExtend,
  onDismiss,
}: {
  pkg: Package;
  remaining: number;
  mode?: "simulation" | "active";
  onExtend: () => void;
  onDismiss: () => void;
}) {
  const insets = useSafeAreaInsets();
  const [secs, setSecs] = useState(remaining);

  useEffect(() => {
    if (remaining <= 0) {
      onDismiss();
      return;
    }
    const t = setInterval(() => {
      setSecs((prev) => {
        if (prev - 1 <= 0) {
          clearInterval(t);
          onDismiss();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <LinearGradient colors={["#2C1A12", "#3E2418"]} style={{ flex: 1 }}>
      <View className="flex-1 items-center px-5" style={{ paddingTop: insets.top + 24, paddingBottom: insets.bottom + 24 }}>
        <View className="items-center mt-10 mb-6">
          <View
            className="w-24 h-24 rounded-full items-center justify-center mb-4"
            style={{ backgroundColor: "rgba(196,92,56,0.30)", borderWidth: 2, borderColor: "rgba(196,92,56,0.4)" }}
          >
            <AlertTriangle size={44} color="#C45C38" strokeWidth={1.5} />
          </View>
          <View className="px-3 py-1 rounded-full mb-3" style={{ backgroundColor: "rgba(196,92,56,0.30)", borderWidth: 1, borderColor: "rgba(196,92,56,0.3)" }}>
            <Text className="text-xs font-sans-semibold uppercase tracking-widest" style={{ color: "#C45C38", letterSpacing: 1.5 }}>
              Time Running Out
            </Text>
          </View>
          <Text className="text-2xl font-serif text-center" style={{ color: "#E8D4B0" }}>
            Your session is{"\n"}about to end
          </Text>
          <Text className="text-sm mt-2 text-center" style={{ color: "#C4A870" }}>
            Don't lose your connection
          </Text>
        </View>

        <View className="w-full rounded-3xl overflow-hidden mb-5" style={{ backgroundColor: "rgba(196,92,56,0.1)", borderWidth: 2, borderColor: "rgba(196,92,56,0.3)" }}>
          <View className="items-center py-6">
            <Text className="text-5xl font-sans-semibold" style={{ color: "#C45C38", letterSpacing: -2 }}>
              {formatTime(secs)}
            </Text>
            <Text className="text-xs mt-2 uppercase tracking-widest" style={{ color: "#C4A870" }}>
              time remaining
            </Text>
            <View className="w-40 h-1.5 rounded-full mt-4 overflow-hidden" style={{ backgroundColor: "rgba(255,255,255,0.1)" }}>
              <View className="h-full rounded-full" style={{ backgroundColor: "#C45C38", width: `${(secs / remaining) * 100}%` }} />
            </View>
          </View>
        </View>

        <View className="w-full rounded-2xl px-4 py-4 mb-5" style={{ backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)" }}>
          <Text className="text-xs font-sans-semibold uppercase tracking-wider mb-3" style={{ color: "#C4A870" }}>
            When time runs out
          </Text>
          {ROWS.map((row, i) => {
            const Icon = row.icon;
            return (
              <View key={row.text} className="flex-row items-center gap-3" style={i < ROWS.length - 1 ? { marginBottom: 10 } : undefined}>
                <View className="w-7 h-7 rounded-lg items-center justify-center" style={{ backgroundColor: "rgba(196,92,56,0.28)" }}>
                  <Icon size={14} color="#C45C38" />
                </View>
                <Text className="text-sm" style={{ color: "#C4A870" }}>
                  {row.text}
                </Text>
              </View>
            );
          })}
        </View>

        <Pressable onPress={onExtend} className="w-full py-4 rounded-2xl mb-3 active:opacity-90" style={{ backgroundColor: "#C45C38" }}>
          <Text className="text-base font-sans-semibold text-center text-white" style={{ letterSpacing: 0.5 }}>
            Extend Now — Stay Connected
          </Text>
        </Pressable>
        <Pressable onPress={onDismiss} className="w-full py-3.5 rounded-2xl active:opacity-80" style={{ backgroundColor: "rgba(255,255,255,0.14)" }}>
          <Text className="text-sm font-sans-semibold text-center" style={{ color: "#9A8060" }}>
            Let it expire
          </Text>
        </Pressable>
        {mode !== "active" && <DemoBadge />}
      </View>
    </LinearGradient>
  );
}

// frontend/src/lib/screens/WarningScreen.svelte
<script>
  import { AlertTriangle, WifiOff, Clock, RotateCcw } from '@lucide/svelte';
  import DemoBadge from '$lib/components/DemoBadge.svelte';
  import { formatTime } from '$lib/data.js';

  let { pkg, remaining, mode = 'simulation', onExtend, onDismiss } = $props();

  let secs = $state(remaining);

  // Read `remaining` (a prop, not the reactive `secs`) in setup so this effect
  // runs once on mount instead of re-subscribing to `secs` every tick.
  $effect(() => {
    if (remaining <= 0) {
      onDismiss();
      return;
    }
    const t = setInterval(() => {
      if (secs - 1 <= 0) {
        clearInterval(t);
        onDismiss();
        secs = 0;
        return;
      }
      secs = secs - 1;
    }, 1000);
    return () => clearInterval(t);
  });

  const rows = [
    { icon: WifiOff, text: 'Internet access will stop' },
    { icon: Clock, text: 'Your session will be archived' },
    { icon: RotateCcw, text: 'You can buy a new session anytime' }
  ];
</script>

<div
  class="flex flex-col items-center px-5 pb-8"
  style="min-height: 100dvh; background: linear-gradient(160deg, #2C1A12 0%, #3E2418 100%);"
>
  <!-- Warning icon -->
  <div class="flex flex-col items-center mt-10 mb-6">
    <div
      class="w-24 h-24 rounded-full flex items-center justify-center mb-4"
      style="background: rgba(196,92,56,0.30); border: 2px solid rgba(196,92,56,0.4); box-shadow: 0 0 40px rgba(196,92,56,0.35);"
    >
      <AlertTriangle size={44} color="#C45C38" strokeWidth={1.5} />
    </div>
    <div class="px-3 py-1 rounded-full mb-3" style="background: rgba(196,92,56,0.30); border: 1px solid rgba(196,92,56,0.3);">
      <span class="text-xs font-bold text-[#C45C38] uppercase tracking-widest">Time Running Out</span>
    </div>
    <h2 class="text-2xl font-bold text-[#E8D4B0] text-center" style="font-family: 'Playfair Display', serif;">
      Your session is<br />about to end
    </h2>
    <p class="text-sm text-[#C4A870] mt-2 text-center">Don't lose your connection</p>
  </div>

  <!-- Countdown -->
  <div class="w-full rounded-3xl overflow-hidden mb-5" style="background: rgba(196,92,56,0.1); border: 2px solid rgba(196,92,56,0.3);">
    <div class="flex flex-col items-center py-6">
      <span class="text-5xl font-bold text-[#C45C38]" style="font-family: 'Inter', sans-serif; letter-spacing: -2px;">
        {formatTime(secs)}
      </span>
      <p class="text-xs text-[#C4A870] mt-2 uppercase tracking-widest">time remaining</p>
      <div class="w-40 h-1.5 rounded-full mt-4 overflow-hidden" style="background: rgba(255,255,255,0.1);">
        <div class="h-full rounded-full bg-[#C45C38]" style="width: {(secs / remaining) * 100}%; transition: width 0.9s linear;"></div>
      </div>
    </div>
  </div>

  <!-- What happens -->
  <div class="w-full rounded-2xl px-4 py-4 mb-5" style="background: rgba(255,255,255,0.12); border: 1px solid rgba(255,255,255,0.18);">
    <p class="text-xs font-semibold text-[#C4A870] uppercase tracking-wider mb-3">When time runs out</p>
    {#each rows as row (row.text)}
      {@const Icon = row.icon}
      <div class="flex items-center gap-3 mb-2.5 last:mb-0">
        <div class="w-7 h-7 rounded-lg flex items-center justify-center shrink-0" style="background: rgba(196,92,56,0.28);">
          <Icon size={14} color="#C45C38" />
        </div>
        <p class="text-sm text-[#C4A870]">{row.text}</p>
      </div>
    {/each}
  </div>

  <button
    onclick={onExtend}
    class="w-full py-4 rounded-2xl font-bold text-base transition-all active:scale-95 mb-3"
    style="background: linear-gradient(135deg, #C45C38, #CC8830); color: #fff; letter-spacing: 0.03em;"
  >
    Extend Now — Stay Connected
  </button>
  <button
    onclick={onDismiss}
    class="w-full py-3.5 rounded-2xl font-semibold text-sm active:scale-95"
    style="background: rgba(255,255,255,0.14); color: #9A8060;"
  >
    Let it expire
  </button>
  {#if mode !== 'active'}<DemoBadge />{/if}
</div>
