// mobile_app/src/components/CampusResources.tsx
// Ported from frontend/src/lib/components/CampusResources.svelte. The
// source's `<a href>` (opens externally, or is a no-op '#' with no
// attachment) becomes expo-web-browser for a link, or a plain disabled-look
// tile with no press handler when there's nothing to open.
import { View, Text, Pressable } from "react-native";
import * as WebBrowser from "expo-web-browser";
import { Link2, ArrowUpRight, Laptop, BookOpen, Wallet, HeartPulse, ShieldAlert, Bus, Home as HomeIcon, Briefcase, GraduationCap, Users, Pin, type LucideIcon } from "lucide-react-native";
import { matchResourceCategory } from "@/lib/campusResourceCategories";
import { recordCampusPostClick } from "@/lib/api";

export type ResourcePost = {
  id: number | string;
  title: string;
  body?: string | null;
  category?: string | null;
  attachment_url?: string | null;
  is_pinned?: boolean;
};

const CATEGORY_ICON: Record<string, LucideIcon> = {
  library: BookOpen,
  it: Laptop,
  finance: Wallet,
  health: HeartPulse,
  security: ShieldAlert,
  transport: Bus,
  housing: HomeIcon,
  careers: Briefcase,
  admissions: GraduationCap,
  student_affairs: Users,
  general: Link2,
};

const DEFAULT_THEME = { bg: "#0b1e13", border: "#12301e", accent: "#c29d53" };

export default function CampusResources({
  post,
  theme = DEFAULT_THEME,
  matchCategory = matchResourceCategory,
  categoryIcons = CATEGORY_ICON,
  recordClick = recordCampusPostClick,
  onOpen,
}: {
  post: ResourcePost;
  theme?: typeof DEFAULT_THEME;
  matchCategory?: typeof matchResourceCategory;
  categoryIcons?: Record<string, LucideIcon>;
  recordClick?: (id: number | string) => void;
  onOpen?: (post: ResourcePost) => void;
}) {
  const category = matchCategory(post.category, post.title);
  const Icon = categoryIcons[category.id] ?? Link2;

  function handlePress() {
    if (onOpen) {
      onOpen(post);
      return;
    }
    if (post.attachment_url) {
      recordClick(post.id);
      WebBrowser.openBrowserAsync(post.attachment_url);
    }
  }

  return (
    <Pressable
      onPress={handlePress}
      disabled={!post.attachment_url && !onOpen}
      className="rounded-xl p-4 flex-row items-start justify-between gap-3 relative"
      style={{ backgroundColor: theme.bg, borderWidth: 1, borderColor: post.is_pinned ? theme.accent : theme.border, opacity: post.attachment_url || onOpen ? 1 : 0.6 }}
    >
      {post.is_pinned && (
        <View className="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full items-center justify-center" style={{ backgroundColor: theme.accent }}>
          <Pin size={9} color={theme.bg} fill={theme.bg} />
        </View>
      )}
      <View className="flex-row items-start gap-3 flex-1 min-w-0">
        <View className="w-9 h-9 rounded-lg items-center justify-center" style={{ backgroundColor: category.color }}>
          <Icon size={15} color="#fdf6e3" />
        </View>
        <View className="min-w-0 flex-1">
          <Text className="text-sm font-sans-semibold leading-snug" numberOfLines={1} style={{ color: "#e5e7eb" }}>
            {post.title}
          </Text>
          {!!post.body && (
            <Text className="text-xs mt-0.5" numberOfLines={2} style={{ color: "#6b7280" }}>
              {post.body}
            </Text>
          )}
        </View>
      </View>
      {!!post.attachment_url && !onOpen && <ArrowUpRight size={12} color="#6b7280" />}
    </Pressable>
  );
}

// frontend/src/lib/components/CampusResources.svelte
<script>
  // Institution-only quick link tile — library, helpdesk, academic calendar,
  // emergency contacts, etc. Renders exactly ONE campus_posts row of
  // type='resource' (TimelineScreen/QuickLinksBoard loop over the filtered
  // list and place each tile as its own grid cell). title is the tile
  // label, attachment_url is the link (an uploaded document or a plain URL
  // typed into the same field — see the admin form's fileOrUrlField), body
  // is an optional description. Icon + accent color come from the post's
  // `category` (matched against RESOURCE_CATEGORIES — see
  // campusResourceCategories.js — with a title-keyword fallback for older
  // resources created before that list existed), so a Security/Emergency
  // tile reads as visually distinct from a Library tile at a glance instead
  // of every tile sharing one generic gold icon. Uses the Campus tab's dark
  // green/gold palette otherwise.
  import { Link2, ArrowUpRight, Laptop, BookOpen, Wallet, HeartPulse, ShieldAlert, Bus, House, Briefcase, GraduationCap, Users, Pin } from '@lucide/svelte';
  import { matchResourceCategory } from '$lib/campusResourceCategories.js';
  import { recordCampusPostClick } from '$lib/api.js';

  let { post } = $props();

  const CATEGORY_ICON = {
    library: BookOpen,
    it: Laptop,
    finance: Wallet,
    health: HeartPulse,
    security: ShieldAlert,
    transport: Bus,
    housing: House,
    careers: Briefcase,
    admissions: GraduationCap,
    student_affairs: Users,
    general: Link2
  };

  const category = $derived(matchResourceCategory(post.category, post.title));
  const Icon = $derived(CATEGORY_ICON[category.id] ?? Link2);

  // Fire-and-forget usage signal for the admin's Quick Links click counts
  // (see campus.js's POST /posts/:id/click) — never blocks the outbound
  // navigation, and skipped entirely for a tile with nothing to actually
  // click through to.
  function handleClick() {
    if (post.attachment_url) recordCampusPostClick(post.id);
  }
</script>

<a
  href={post.attachment_url || '#'}
  target={post.attachment_url ? '_blank' : undefined}
  rel="noopener noreferrer"
  onclick={handleClick}
  class="quick-link-tile group rounded-xl p-4 flex items-start justify-between gap-3 transition-all relative"
  class:pinned-tile={post.is_pinned}
  style="background: #0b1e13; border: 1px solid {post.is_pinned ? '#c29d53' : '#12301e'}; opacity: {post.attachment_url ? 1 : 0.6};"
>
  {#if post.is_pinned}
    <div class="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full flex items-center justify-center" style="background: #c29d53; box-shadow: 0 0 0 2px #0b1e13;">
      <Pin size={9} color="#0b1e13" fill="#0b1e13" />
    </div>
  {/if}
  <div class="flex items-start gap-3 min-w-0">
    <div class="w-9 h-9 rounded-lg flex items-center justify-center shrink-0" style="background: linear-gradient(135deg, {category.color}, {category.color}bb);">
      <Icon size={15} color="#fdf6e3" />
    </div>
    <div class="min-w-0">
      <p class="text-sm font-semibold leading-snug truncate" style="color: #e5e7eb;">{post.title}</p>
      {#if post.body}
        <p class="text-xs mt-0.5 line-clamp-2" style="color: #6b7280;">{post.body}</p>
      {/if}
    </div>
  </div>
  {#if post.attachment_url}
    <ArrowUpRight size={12} color="#6b7280" class="shrink-0 mt-1 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
  {/if}
</a>

<style>
  .quick-link-tile:hover {
    border-color: #1c492e !important;
  }
  .quick-link-tile.pinned-tile:hover {
    border-color: #d4af6a !important;
  }
</style>
