// mobile_app/src/components/CampusEventsStrip.tsx
// Ported from frontend/src/lib/components/CampusEventsStrip.svelte.
import { useState } from "react";
import { View, Text, Pressable, Modal } from "react-native";
import { MapPin, CalendarDays, Clock, X, Pin } from "lucide-react-native";
import type { NoticeTheme } from "@/components/NoticeBoard";

export type EventPost = {
  id: number | string;
  title: string;
  category?: string | null;
  location?: string | null;
  body?: string | null;
  is_pinned?: boolean;
  event_starts_at: string;
  event_ends_at?: string | null;
};

const DEFAULT_THEME: NoticeTheme & { borderHover: string; accentGradA: string; accentGradB: string } = {
  bg: "#0b1e13",
  bgAlt: "#0a1b11",
  border: "#12301e",
  borderAlt: "#163a23",
  borderHover: "#1c492e",
  accent: "#c29d53",
  accentSoft: "rgba(194,157,83,0.18)",
  accentGradA: "#d4af6a",
  accentGradB: "#8b6a35",
  bannerGradA: "#123420",
  bannerGradB: "#0d2317",
  bannerBorder: "#1c472e",
};

function dayNum(iso: string) {
  return new Date(iso).getDate();
}
function monthAbbrev(iso: string) {
  return new Date(iso).toLocaleDateString(undefined, { month: "short" });
}
function timeRange(startIso: string, endIso?: string | null) {
  const opts: Intl.DateTimeFormatOptions = { hour: "numeric", minute: "2-digit" };
  const start = new Date(startIso).toLocaleTimeString(undefined, opts);
  if (!endIso) return start;
  return `${start} – ${new Date(endIso).toLocaleTimeString(undefined, opts)}`;
}
function relativeLabel(iso: string) {
  const now = new Date();
  const target = new Date(iso);
  const startOfDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
  const diffDays = Math.round((startOfDay(target) - startOfDay(now)) / 86400000);
  if (diffDays < 0) return "Past";
  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Tomorrow";
  return `in ${diffDays}d`;
}

export default function CampusEventsStrip({ posts = [], theme = DEFAULT_THEME }: { posts?: EventPost[]; theme?: typeof DEFAULT_THEME }) {
  const [selected, setSelected] = useState<EventPost | null>(null);

  if (posts.length === 0) return null;

  return (
    <>
      <View style={{ gap: 12 }}>
        {posts.map((post) => (
          <Pressable
            key={post.id}
            onPress={() => setSelected(post)}
            className="rounded-xl p-4 relative"
            style={{ backgroundColor: theme.bg, borderWidth: 1, borderColor: post.is_pinned ? theme.accent : theme.border }}
          >
            {post.is_pinned && (
              <View className="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full items-center justify-center" style={{ backgroundColor: theme.accent }}>
                <Pin size={9} color={theme.bg} fill={theme.bg} />
              </View>
            )}
            <View className="flex-row items-center gap-3">
              <View className="items-center justify-center rounded-lg px-3 py-1.5" style={{ backgroundColor: theme.accentGradA, minWidth: 56 }}>
                <Text className="text-[10px] uppercase" style={{ color: "#fdf6e3" }}>
                  {monthAbbrev(post.event_starts_at)}
                </Text>
                <Text className="text-xl font-sans-semibold leading-none my-0.5" style={{ color: "#fdf6e3" }}>
                  {dayNum(post.event_starts_at)}
                </Text>
              </View>
              <View className="flex-1 min-w-0">
                <View className="flex-row items-center gap-1.5">
                  <CalendarDays size={10} color="#9ca3af" />
                  <Text className="text-[11px]" style={{ color: "#9ca3af" }}>
                    {relativeLabel(post.event_starts_at)}
                  </Text>
                </View>
                <Text className="text-sm font-sans-semibold mt-0.5" numberOfLines={1} style={{ color: "#f3f4f6" }}>
                  {post.title}
                </Text>
                {!!post.location && (
                  <View className="flex-row items-center gap-1 mt-1">
                    <MapPin size={10} color="#6b7280" />
                    <Text className="text-xs" numberOfLines={1} style={{ color: "#6b7280" }}>
                      {post.location}
                    </Text>
                  </View>
                )}
              </View>
            </View>
          </Pressable>
        ))}
      </View>

      <Modal visible={!!selected} transparent animationType="fade" onRequestClose={() => setSelected(null)}>
        <Pressable className="flex-1 items-center justify-center px-4" style={{ backgroundColor: "rgba(0,0,0,0.65)" }} onPress={() => setSelected(null)}>
          <Pressable className="w-full rounded-3xl" style={{ backgroundColor: theme.bg, maxWidth: 480, maxHeight: "85%", borderWidth: 1, borderColor: theme.border }} onPress={(e) => e.stopPropagation()}>
            {selected && (
              <>
                <View className="flex-row items-center justify-between px-5 py-4" style={{ borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.08)" }}>
                  <Text className="text-sm font-sans-semibold" style={{ color: "#f3f4f6" }}>
                    Campus Event
                  </Text>
                  <Pressable onPress={() => setSelected(null)} className="w-8 h-8 rounded-full items-center justify-center" style={{ backgroundColor: "rgba(255,255,255,0.08)" }}>
                    <X size={14} color="#9ca3af" />
                  </Pressable>
                </View>
                <View className="px-5 py-4" style={{ gap: 12 }}>
                  <View className="flex-row items-center gap-3">
                    <View className="items-center justify-center rounded-lg px-3 py-2" style={{ backgroundColor: theme.border, borderWidth: 1, borderColor: theme.borderHover }}>
                      <Text className="text-[10px] uppercase" style={{ color: "#9ca3af" }}>
                        {monthAbbrev(selected.event_starts_at)}
                      </Text>
                      <Text className="text-xl font-sans-semibold leading-none my-0.5" style={{ color: theme.accent }}>
                        {dayNum(selected.event_starts_at)}
                      </Text>
                    </View>
                    <View className="flex-1 min-w-0">
                      <View className="flex-row items-center gap-1.5">
                        <Text className="text-base font-serif" style={{ color: "#f3f4f6" }}>
                          {selected.title}
                        </Text>
                        {selected.is_pinned && <Pin size={12} color={theme.accent} fill={theme.accent} />}
                      </View>
                      {!!selected.category && (
                        <Text className="text-[11px] mt-0.5" style={{ color: "#9ca3af" }}>
                          {selected.category}
                        </Text>
                      )}
                    </View>
                  </View>
                  <View className="flex-row items-center gap-1.5">
                    <Clock size={12} color="#9ca3af" />
                    <Text className="text-xs" style={{ color: "#d1d5db" }}>
                      {timeRange(selected.event_starts_at, selected.event_ends_at)}
                    </Text>
                  </View>
                  {!!selected.location && (
                    <View className="flex-row items-center gap-1.5">
                      <MapPin size={12} color="#9ca3af" />
                      <Text className="text-xs" style={{ color: "#d1d5db" }}>
                        {selected.location}
                      </Text>
                    </View>
                  )}
                  {!!selected.body && (
                    <Text className="text-[12.5px] leading-relaxed" style={{ color: "#d1d5db" }}>
                      {selected.body}
                    </Text>
                  )}
                </View>
              </>
            )}
          </Pressable>
        </Pressable>
      </Modal>
    </>
  );
}

// frontend/src/lib/components/CampusEventsStrip.svelte
<script>
  // Institution-only Campus Events list — full-width cards, soonest-first
  // (see services/campusPosts.js's listActivePosts, which orders
  // type='event' posts by event_starts_at). Stacked vertically at full
  // width rather than a horizontal scroll strip, so it matches Exam
  // Timetable's full-width trigger card next to it. Uses the Campus tab's
  // dark green/gold palette. Uses its own lightweight detail sheet rather
  // than the shared AdminModal, since this is a client-facing screen, not
  // the admin dashboard.
  import { MapPin, CalendarDays, Clock, X, Pin } from '@lucide/svelte';

  // Theme defaults to today's look — a different vertical (e.g. Community)
  // can pass its own palette; every call site that omits `theme` renders
  // exactly as before this prop existed.
  const DEFAULT_THEME = {
    bg: '#0b1e13',
    border: '#12301e',
    borderHover: '#1c492e',
    accent: '#c29d53',
    accentGradA: '#d4af6a',
    accentGradB: '#8b6a35'
  };

  let { posts = [], theme = DEFAULT_THEME } = $props();

  let selected = $state(null);

  function dayNum(iso) {
    return new Date(iso).getDate();
  }
  function monthAbbrev(iso) {
    return new Date(iso).toLocaleDateString(undefined, { month: 'short' });
  }
  function timeRange(startIso, endIso) {
    const opts = { hour: 'numeric', minute: '2-digit' };
    const start = new Date(startIso).toLocaleTimeString(undefined, opts);
    if (!endIso) return start;
    return `${start} – ${new Date(endIso).toLocaleTimeString(undefined, opts)}`;
  }

  // "Today" / "Tomorrow" / "in Nd" — read at a glance, matching how a
  // student actually thinks about an upcoming date rather than a raw one.
  function relativeLabel(iso) {
    const now = new Date();
    const target = new Date(iso);
    const startOfDay = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
    const diffDays = Math.round((startOfDay(target) - startOfDay(now)) / 86400000);
    if (diffDays < 0) return 'Past';
    if (diffDays === 0) return 'Today';
    if (diffDays === 1) return 'Tomorrow';
    return `in ${diffDays}d`;
  }
</script>

{#if posts.length > 0}
  <!-- With exactly one event (the common case), this stretches to match
       Exam Timetable's h-full sibling column instead of top-aligning with
       dead space below — with several events, natural stacking height is
       correct instead and this is skipped. -->
  <div class="flex flex-col gap-3" class:h-full={posts.length === 1}>
    {#each posts as post (post.id)}
      <button
        type="button"
        onclick={() => (selected = post)}
        class="event-trigger w-full text-left rounded-xl p-4 transition-all active:scale-[0.98] relative"
        class:h-full={posts.length === 1}
        style="background: {theme.bg}; border: 1px solid {post.is_pinned ? theme.accent : theme.border}; --es-border-hover: {theme.borderHover};"
      >
        {#if post.is_pinned}
          <div class="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full flex items-center justify-center" style="background: {theme.accent}; box-shadow: 0 0 0 2px {theme.bg};">
            <Pin size={9} color={theme.bg} fill={theme.bg} />
          </div>
        {/if}
        <div class="flex items-center gap-3" class:h-full={posts.length === 1}>
          <div class="flex flex-col items-center justify-center rounded-lg px-3 py-1.5 shrink-0" style="background: linear-gradient(135deg, {theme.accentGradA}, {theme.accentGradB}); min-width: 56px;">
            <span class="text-[10px] uppercase tracking-tight" style="color: #fdf6e3;">{monthAbbrev(post.event_starts_at)}</span>
            <span class="text-xl font-bold leading-none my-0.5" style="color: #fdf6e3;">{dayNum(post.event_starts_at)}</span>
          </div>
          <div class="min-w-0">
            <div class="flex items-center gap-1.5" style="color: #9ca3af;">
              <CalendarDays size={10} />
              <span class="text-[11px]">{relativeLabel(post.event_starts_at)}</span>
            </div>
            <p class="text-sm font-bold leading-snug truncate mt-0.5" style="color: #f3f4f6;">{post.title}</p>
            {#if post.location}
              <div class="flex items-center gap-1 mt-1" style="color: #6b7280;">
                <MapPin size={10} class="shrink-0" />
                <span class="text-xs truncate">{post.location}</span>
              </div>
            {/if}
          </div>
        </div>
      </button>
    {/each}
  </div>
{/if}

{#if selected}
  <div class="fixed inset-0 z-[100] flex items-center justify-center p-4" style="background: rgba(0,0,0,0.65);">
    <div class="w-full rounded-3xl shadow-2xl flex flex-col" style="background: {theme.bg}; max-width: 480px; max-height: 90vh; border: 1px solid {theme.border};">
      <div class="flex items-center justify-between px-5 py-4 shrink-0" style="border-bottom: 1px solid rgba(255,255,255,0.08);">
        <p class="text-sm font-bold" style="color: #f3f4f6;">Campus Event</p>
        <button
          onclick={() => (selected = null)}
          aria-label="Close"
          class="w-8 h-8 rounded-full flex items-center justify-center shrink-0"
          style="background: rgba(255,255,255,0.08);"
        >
          <X size={14} color="#9ca3af" />
        </button>
      </div>
      <div class="px-5 py-4 flex flex-col gap-3 overflow-y-auto">
        <div class="flex items-center gap-3">
          <div class="flex flex-col items-center justify-center rounded-lg px-3 py-2 shrink-0" style="background: {theme.border}; border: 1px solid {theme.borderHover};">
            <span class="text-[10px] uppercase tracking-tight" style="color: #9ca3af;">{monthAbbrev(selected.event_starts_at)}</span>
            <span class="text-xl font-bold leading-none my-0.5" style="color: {theme.accent};">{dayNum(selected.event_starts_at)}</span>
          </div>
          <div class="flex-1 min-w-0">
            <p class="text-base font-bold leading-snug flex items-center gap-1.5" style="color: #f3f4f6; font-family: 'Playfair Display', serif;">
              {selected.title}
              {#if selected.is_pinned}<Pin size={12} color={theme.accent} fill={theme.accent} class="shrink-0" />{/if}
            </p>
            {#if selected.category}<p class="text-[11px] mt-0.5" style="color: #9ca3af;">{selected.category}</p>{/if}
          </div>
        </div>
        <div class="flex items-center gap-1.5 text-[12px]" style="color: #d1d5db;">
          <Clock size={12} color="#9ca3af" />
          {timeRange(selected.event_starts_at, selected.event_ends_at)}
        </div>
        {#if selected.location}
          <div class="flex items-center gap-1.5 text-[12px]" style="color: #d1d5db;">
            <MapPin size={12} color="#9ca3af" />
            {selected.location}
          </div>
        {/if}
        {#if selected.body}
          <p class="text-[12.5px] leading-relaxed mt-1" style="color: #d1d5db;">{selected.body}</p>
        {/if}
      </div>
    </div>
  </div>
{/if}

<style>
  .event-trigger:hover {
    border-color: var(--es-border-hover, #1c492e) !important;
  }
</style>
