// mobile_app/src/components/MultiLineChartMini.tsx
// RN port of frontend/src/lib/components/MultiLineChartMini.svelte — the
// multi-series sibling of AreaChartMini, one line per series (no fill area;
// several overlapping fills would read as noise rather than signal), sharing
// a single y-scale across all series so line heights stay comparable. Same
// viewBox="0 0 100 100" + preserveAspectRatio="none" scaling trick via
// react-native-svg as AreaChartMini.
import { View, Text } from "react-native";
import Svg, { Path } from "react-native-svg";

export type LineSeries = { siteId?: string | number | null; siteName: string; data: number[] };

const DEFAULT_COLORS = ["#C45C38", "#5B8ED6", "#4E8050", "#CC8830", "#B565A7", "#5AAFAE"];

export default function MultiLineChartMini({
  days = [],
  series = [],
  colors = DEFAULT_COLORS,
  height = 160,
  showGrid = true,
  showXLabels = true,
  showYLabels = true,
  showLegend = true,
  yAxisWidth = 32,
  labelColor = "#AECAAE",
  labelSize = 9,
}: {
  days?: string[];
  series?: LineSeries[];
  colors?: string[];
  height?: number;
  showGrid?: boolean;
  showXLabels?: boolean;
  showYLabels?: boolean;
  showLegend?: boolean;
  yAxisWidth?: number;
  labelColor?: string;
  labelSize?: number;
}) {
  const n = days.length;
  const max = Math.max(0.0001, ...series.flatMap((s) => s.data.map((v) => Number(v) || 0)));

  function formatAxisValue(v: number): string {
    if (v >= 1000) return `${(v / 1000).toFixed(v >= 10000 ? 0 : 1)}k`;
    if (v >= 10 || Number.isInteger(v)) return String(Math.round(v));
    return v.toFixed(1);
  }

  function yv(val: number): number {
    return 98 - (val / max) * 92;
  }
  function xv(i: number): number {
    return n <= 1 ? 0 : (i / (n - 1)) * 100;
  }

  function linePath(data: number[]): string {
    return data.map((v, i) => `${i === 0 ? "M" : "L"} ${xv(i)} ${yv(Number(v) || 0)}`).join(" ");
  }

  let labelIdx: number[] = [];
  if (n > 0) {
    if (n <= 7) {
      labelIdx = days.map((_, i) => i);
    } else {
      const step = Math.ceil(n / 6);
      for (let i = 0; i < n; i += step) labelIdx.push(i);
      if (labelIdx[labelIdx.length - 1] !== n - 1) labelIdx.push(n - 1);
    }
  }

  function formatDay(dateStr: string): string {
    return new Date(`${dateStr}T00:00:00Z`).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
  }

  return (
    <View style={{ width: "100%", flexDirection: "column" }}>
      <View style={{ height, flexDirection: "column" }}>
        <View style={{ flex: 1, minHeight: 0, flexDirection: "row" }}>
          {showYLabels && (
            <View style={{ width: yAxisWidth, flexShrink: 0 }}>
              {[0, 25, 50, 75, 100].map((g) => (
                <Text
                  key={g}
                  numberOfLines={1}
                  style={{ position: "absolute", right: 4, top: `${g}%`, transform: [{ translateY: -6 }], color: labelColor, fontSize: labelSize }}
                >
                  {formatAxisValue(max * (1 - g / 100))}
                </Text>
              ))}
            </View>
          )}
          <View style={{ flex: 1, minHeight: 0, position: "relative" }}>
            {showGrid &&
              [0, 25, 50, 75, 100].map((g) => (
                <View
                  key={g}
                  style={{ position: "absolute", left: 0, right: 0, top: `${g}%`, borderTopWidth: 1, borderStyle: "dashed", borderTopColor: "rgba(255,255,255,0.12)" }}
                />
              ))}
            <Svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{ position: "absolute", left: 0, right: 0, top: 0, bottom: 0, width: "100%", height: "100%" }}>
              {series.map((s, i) => (
                <Path
                  key={s.siteId ?? i}
                  d={linePath(s.data)}
                  fill="none"
                  stroke={colors[i % colors.length]}
                  strokeWidth={2.5}
                  strokeLinejoin="round"
                  strokeLinecap="round"
                  vectorEffect="non-scaling-stroke"
                />
              ))}
            </Svg>
          </View>
        </View>
        {showXLabels && n > 0 && (
          <View style={{ flexDirection: "row" }}>
            {showYLabels && <View style={{ width: yAxisWidth, flexShrink: 0 }} />}
            <View style={{ flex: 1, minWidth: 0, position: "relative", height: 14, marginTop: 2 }}>
              {labelIdx.map((i) => (
                <Text
                  key={i}
                  numberOfLines={1}
                  style={{ position: "absolute", left: `${xv(i)}%`, transform: [{ translateX: -10 }], color: labelColor, fontSize: labelSize }}
                >
                  {formatDay(days[i])}
                </Text>
              ))}
            </View>
          </View>
        )}
      </View>

      {showLegend && series.length > 0 && (
        <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 10, paddingLeft: showYLabels ? yAxisWidth : 0 }}>
          {series.map((s, i) => (
            <View key={s.siteId ?? i} style={{ flexDirection: "row", alignItems: "center", gap: 5 }}>
              <View style={{ width: 8, height: 8, borderRadius: 4, backgroundColor: colors[i % colors.length] }} />
              <Text style={{ fontSize: labelSize, color: labelColor }}>{s.siteName}</Text>
            </View>
          ))}
        </View>
      )}
    </View>
  );
}

// frontend/src/lib/components/MultiLineChartMini.svelte
<script>
  // Multi-series sibling of AreaChartMini — one line per series (no fill,
  // area shading from several overlapping series reads as noise rather
  // than signal), sharing a single y-scale across all of them so line
  // heights stay comparable. Same hand-rolled SVG conventions as the other
  // *Mini chart components: viewBox="0 0 100 100", non-scaling stroke.
  let {
    days = [],
    series = [], // [{ siteId, siteName, data: number[] }] — data[i] aligns with days[i]
    colors = ['#C45C38', '#5B8ED6', '#4E8050', '#CC8830', '#B565A7', '#5AAFAE'],
    height = 160,
    showGrid = true,
    showXLabels = true,
    showYLabels = true,
    showLegend = true,
    yAxisWidth = 32,
    labelColor = '#AECAAE',
    labelSize = 9
  } = $props();

  const n = $derived(days.length);
  const max = $derived(Math.max(0.0001, ...series.flatMap((s) => s.data.map((v) => Number(v) || 0))));

  function formatAxisValue(v) {
    if (v >= 1000) return `${(v / 1000).toFixed(v >= 10000 ? 0 : 1)}k`;
    if (v >= 10 || Number.isInteger(v)) return String(Math.round(v));
    return v.toFixed(1);
  }

  function yv(val) {
    return 98 - (val / max) * 92;
  }
  function xv(i) {
    return n <= 1 ? 0 : (i / (n - 1)) * 100;
  }

  function linePath(data) {
    return data.map((v, i) => `${i === 0 ? 'M' : 'L'} ${xv(i)} ${yv(Number(v) || 0)}`).join(' ');
  }

  const labelIdx = $derived.by(() => {
    if (n === 0) return [];
    if (n <= 7) return days.map((_, i) => i);
    const step = Math.ceil(n / 6);
    const idx = [];
    for (let i = 0; i < n; i += step) idx.push(i);
    if (idx[idx.length - 1] !== n - 1) idx.push(n - 1);
    return idx;
  });

  function formatDay(dateStr) {
    return new Date(`${dateStr}T00:00:00Z`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' });
  }
</script>

<div style="width: 100%; display: flex; flex-direction: column;">
  <div style="height: {height}px; display: flex; flex-direction: column;">
    <div style="flex: 1; min-height: 0; display: flex;">
      {#if showYLabels}
        <div style="position: relative; width: {yAxisWidth}px; flex-shrink: 0;">
          {#each [0, 25, 50, 75, 100] as g}
            <span
              style="position: absolute; right: 4px; top: {g}%; transform: translateY(-50%); color: {labelColor}; font-size: {labelSize}px; white-space: nowrap;"
              >{formatAxisValue(max * (1 - g / 100))}</span
            >
          {/each}
        </div>
      {/if}
      <div style="flex: 1; min-height: 0; position: relative;">
        {#if showGrid}
          {#each [0, 25, 50, 75, 100] as g}
            <div style="position: absolute; left: 0; right: 0; top: {g}%; border-top: 1px dashed rgba(255,255,255,0.12);"></div>
          {/each}
        {/if}
        <svg viewBox="0 0 100 100" preserveAspectRatio="none" style="display: block; position: absolute; inset: 0; width: 100%; height: 100%;">
          {#each series as s, i (s.siteId ?? i)}
            <path
              d={linePath(s.data)}
              fill="none"
              stroke={colors[i % colors.length]}
              stroke-width="2.5"
              stroke-linejoin="round"
              stroke-linecap="round"
              vector-effect="non-scaling-stroke"
            />
          {/each}
        </svg>
      </div>
    </div>
    {#if showXLabels && n > 0}
      <div style="display: flex;">
        {#if showYLabels}<div style="width: {yAxisWidth}px; flex-shrink: 0;"></div>{/if}
        <div style="flex: 1; min-width: 0; position: relative; height: 14px; margin-top: 2px;">
          {#each labelIdx as i}
            <span
              style="position: absolute; left: {xv(i)}%; transform: translateX(-50%); color: {labelColor}; font-size: {labelSize}px; white-space: nowrap;"
              >{formatDay(days[i])}</span
            >
          {/each}
        </div>
      </div>
    {/if}
  </div>

  {#if showLegend && series.length > 0}
    <div style="display: flex; flex-wrap: wrap; gap: 10px; margin-top: 10px; padding-left: {showYLabels ? yAxisWidth : 0}px;">
      {#each series as s, i (s.siteId ?? i)}
        <div style="display: flex; align-items: center; gap: 5px;">
          <span style="width: 8px; height: 8px; border-radius: 50%; background: {colors[i % colors.length]}; flex-shrink: 0;"></span>
          <span style="font-size: {labelSize}px; color: {labelColor};">{s.siteName}</span>
        </div>
      {/each}
    </div>
  {/if}
</div>
