// mobile_app/src/components/NoticeBoard.tsx
// Ported from frontend/src/lib/components/NoticeBoard.svelte. The source's
// canvas-based flood-fill transparency cutout on /pin.webp (built at
// runtime) has no RN equivalent and isn't needed anyway — this just uses
// lucide's Pin icon directly instead of a custom pin graphic.
import { useState } from "react";
import { View, Text, Pressable, Modal, TextInput, ScrollView } from "react-native";
import { Pin, FileText, Megaphone, ExternalLink, ChevronDown, ChevronRight, Search, X } from "lucide-react-native";
import * as WebBrowser from "expo-web-browser";

export type NoticePost = {
  id: number | string;
  type: "notice" | "release";
  title: string;
  body?: string | null;
  category?: string | null;
  priority?: "normal" | "important" | "urgent";
  is_pinned?: boolean;
  attachment_url?: string | null;
  event_starts_at?: string | null;
  published_at: string;
};

export type NoticeTheme = {
  bg: string;
  bgAlt: string;
  border: string;
  borderAlt: string;
  accent: string;
  accentSoft: string;
  accentGradA: string;
  accentGradB: string;
  bannerGradA: string;
  bannerGradB: string;
  bannerBorder: string;
};

const DEFAULT_THEME: NoticeTheme = {
  bg: "#0b1e13",
  bgAlt: "#0a1b11",
  border: "#12301e",
  borderAlt: "#163a23",
  accent: "#c29d53",
  accentSoft: "rgba(194,157,83,0.18)",
  accentGradA: "#d4af6a",
  accentGradB: "#8b6a35",
  bannerGradA: "#123420",
  bannerGradB: "#0d2317",
  bannerBorder: "#1c472e",
};

const PRIORITY_COLOR: Record<string, string> = { urgent: "#C45C38", important: "#c29d53", normal: "#5b6b60" };
const TYPE_LABEL: Record<string, string> = { notice: "Notice", release: "Release" };

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

export default function NoticeBoard({
  posts = [],
  pastPosts = [],
  theme = DEFAULT_THEME,
  readIds = new Set<number | string>(),
  onMarkRead = () => {},
}: {
  posts?: NoticePost[];
  pastPosts?: NoticePost[];
  theme?: NoticeTheme;
  readIds?: Set<number | string>;
  onMarkRead?: (id: number | string) => void;
}) {
  const [modalOpen, setModalOpen] = useState(false);
  const [expandedId, setExpandedId] = useState<number | string | null>(null);
  const [activeTab, setActiveTab] = useState<"all" | "current" | "past">("current");
  const [query, setQuery] = useState("");

  const visiblePosts = activeTab === "all" ? [...posts, ...pastPosts] : activeTab === "current" ? posts : pastPosts;
  const q = query.trim().toLowerCase();
  const filteredVisiblePosts = !q
    ? visiblePosts
    : visiblePosts.filter((p) => [p.title, p.category, p.body].some((f) => (f || "").toLowerCase().includes(q)));

  const topPost = posts[0];
  const urgentCount = posts.filter((p) => p.priority === "urgent").length;
  const unreadCount = posts.filter((p) => !readIds.has(p.id)).length;

  function toggle(id: number | string) {
    const next = expandedId === id ? null : id;
    setExpandedId(next);
    if (next === id && !readIds.has(id)) onMarkRead(id);
  }

  function openModal() {
    setModalOpen(true);
    setExpandedId(null);
    setQuery("");
    setActiveTab(posts.length > 0 ? "current" : "past");
  }

  if (posts.length === 0 && pastPosts.length === 0) return null;

  return (
    <>
      <Pressable
        onPress={openModal}
        className="w-full rounded-2xl overflow-hidden"
        style={{ backgroundColor: theme.bannerGradA, borderWidth: 1, borderColor: theme.bannerBorder }}
      >
        <View className="flex-row items-center gap-3.5 px-5 py-4">
          <View className="w-11 h-11 rounded-xl items-center justify-center relative" style={{ backgroundColor: theme.accentGradA }}>
            <Pin size={20} color="#fdf6e3" fill="#fdf6e3" />
            {unreadCount > 0 && (
              <View className="absolute -top-1 -right-1 w-4 h-4 rounded-full items-center justify-center" style={{ backgroundColor: "#C45C38" }}>
                <Text className="text-white text-[9px] font-sans-semibold">{unreadCount > 9 ? "9+" : unreadCount}</Text>
              </View>
            )}
          </View>
          <View className="flex-1 min-w-0">
            <View className="flex-row items-center gap-2 mb-1">
              <Text className="text-xs font-sans-semibold uppercase tracking-wider" style={{ color: theme.accent }}>
                Notice Board
              </Text>
              {urgentCount > 0 && (
                <View className="px-1.5 py-0.5 rounded-full" style={{ backgroundColor: "rgba(196,92,56,0.22)" }}>
                  <Text className="text-[9px] font-sans-semibold uppercase" style={{ color: "#E08A6A" }}>
                    {urgentCount} urgent
                  </Text>
                </View>
              )}
            </View>
            <Text className="text-sm font-sans-semibold" numberOfLines={1} style={{ color: posts.length > 0 ? "#f3f4f6" : "#9ca3af" }}>
              {posts.length > 0 ? topPost?.title : "No current notices"}
            </Text>
          </View>
          <View className="items-end gap-1.5">
            <View className="flex-row items-center gap-1 px-2.5 py-1.5 rounded-full" style={{ backgroundColor: theme.accentSoft }}>
              <Text className="text-[10px] font-sans-semibold" style={{ color: theme.accent }}>
                View all
              </Text>
              <ChevronRight size={11} color={theme.accent} />
            </View>
            <Text className="text-[10px]" style={{ color: "#6b7280" }}>
              {posts.length > 0 ? (unreadCount > 0 ? `${unreadCount} unread` : `${posts.length} notice${posts.length === 1 ? "" : "s"}`) : `${pastPosts.length} past`}
            </Text>
          </View>
        </View>
      </Pressable>

      <Modal visible={modalOpen} animationType="slide" transparent onRequestClose={() => setModalOpen(false)}>
        <Pressable className="flex-1 justify-end" style={{ backgroundColor: "rgba(0,0,0,0.65)" }} onPress={() => setModalOpen(false)}>
          <Pressable style={{ backgroundColor: theme.bg, maxHeight: "85%", borderTopLeftRadius: 24, borderTopRightRadius: 24 }} onPress={(e) => e.stopPropagation()}>
            <View className="flex-row items-center justify-between px-5 pt-5 pb-3" style={{ borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.08)" }}>
              <View>
                <Text className="text-[10px] font-sans-semibold uppercase tracking-[3px]" style={{ color: theme.accent }}>
                  Notice Board
                </Text>
                <Text className="text-[11px] mt-0.5" style={{ color: "#9ca3af" }}>
                  {filteredVisiblePosts.length} of {visiblePosts.length} notices
                </Text>
              </View>
              <Pressable onPress={() => setModalOpen(false)} className="w-8 h-8 rounded-full items-center justify-center" style={{ backgroundColor: "rgba(255,255,255,0.08)" }}>
                <X size={14} color="#9ca3af" />
              </Pressable>
            </View>

            <View className="flex-row gap-2 px-5 pt-3">
              {(["all", "current", "past"] as const).map((tab) => (
                <Pressable
                  key={tab}
                  onPress={() => setActiveTab(tab)}
                  className="px-3 py-1.5 rounded-full"
                  style={{
                    backgroundColor: activeTab === tab ? theme.accent : theme.bgAlt,
                    borderWidth: activeTab === tab ? 0 : 1,
                    borderColor: theme.borderAlt,
                  }}
                >
                  <Text className="text-[11px] font-sans-semibold" style={{ color: activeTab === tab ? theme.bg : "#9ca3af" }}>
                    {tab === "all" ? `All (${posts.length + pastPosts.length})` : tab === "current" ? `Current (${posts.length})` : `Past (${pastPosts.length})`}
                  </Text>
                </Pressable>
              ))}
            </View>

            <View className="px-5 pt-3 pb-3">
              <View className="flex-row items-center gap-2 rounded-lg px-3.5 py-2.5" style={{ backgroundColor: theme.bgAlt, borderWidth: 1, borderColor: theme.borderAlt }}>
                <Search size={14} color={theme.accent} />
                <TextInput value={query} onChangeText={setQuery} placeholder="Search notices…" placeholderTextColor="#6b7280" className="flex-1 text-sm" style={{ color: "#e5e7eb" }} />
                {!!query && (
                  <Pressable onPress={() => setQuery("")}>
                    <X size={13} color="#9ca3af" />
                  </Pressable>
                )}
              </View>
            </View>

            <ScrollView className="px-5 pb-4" style={{ gap: 10 }}>
              {filteredVisiblePosts.length === 0 ? (
                <Text className="text-sm text-center py-8" style={{ color: "#9ca3af" }}>
                  {query ? `No notices match "${query}".` : activeTab === "all" ? "No notices yet." : `No ${activeTab} notices.`}
                </Text>
              ) : (
                filteredVisiblePosts.map((post) => {
                  const color = PRIORITY_COLOR[post.priority ?? "normal"] ?? PRIORITY_COLOR.normal;
                  const open = expandedId === post.id;
                  const isRead = readIds.has(post.id);
                  return (
                    <Pressable
                      key={post.id}
                      onPress={() => toggle(post.id)}
                      className="rounded-xl overflow-hidden mb-2.5"
                      style={{ backgroundColor: "rgba(255,255,255,0.04)", borderLeftWidth: 3, borderLeftColor: color, opacity: isRead ? 0.65 : 1 }}
                    >
                      <View className="flex-row items-start gap-3 px-4 py-3.5">
                        <View className="w-8 h-8 rounded-lg items-center justify-center mt-0.5" style={{ backgroundColor: `${color}30` }}>
                          <Megaphone size={14} color={color} />
                        </View>
                        <View className="flex-1 min-w-0">
                          <View className="flex-row items-center gap-1.5 flex-wrap mb-1">
                            <View className="px-1.5 py-0.5 rounded" style={{ backgroundColor: `${color}25` }}>
                              <Text className="text-[9px] font-sans-semibold uppercase" style={{ color }}>
                                {TYPE_LABEL[post.type] ?? post.type}
                              </Text>
                            </View>
                            {!!post.category && (
                              <Text className="text-[10px]" style={{ color: "#9ca3af" }}>
                                {post.category}
                              </Text>
                            )}
                            {post.is_pinned && <Pin size={10} color={theme.accent} fill={theme.accent} />}
                          </View>
                          <View className="flex-row items-center gap-1.5">
                            {!isRead && <View className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: theme.accent }} />}
                            <Text className="text-sm flex-1" style={{ color: "#f3f4f6", fontWeight: isRead ? "500" : "700" }}>
                              {post.title}
                            </Text>
                          </View>
                          {!open && !!post.body && (
                            <Text className="text-[11px] mt-0.5" numberOfLines={1} style={{ color: "#6b7280" }}>
                              {post.body}
                            </Text>
                          )}
                        </View>
                        <View className="items-end gap-1">
                          <Text className="text-[10px]" style={{ color: "#6b7280" }}>
                            {formatDate(post.published_at)}
                          </Text>
                          <ChevronDown size={13} color="#6b7280" style={{ transform: [{ rotate: open ? "180deg" : "0deg" }] }} />
                        </View>
                      </View>

                      {open && (
                        <View className="px-4 pb-4" style={{ paddingLeft: 52 }}>
                          {!!post.event_starts_at && (
                            <Text className="text-[11px] mb-2" style={{ color: "#9ca3af" }}>
                              {new Date(post.event_starts_at) < new Date() ? "Expired" : "Relevant until"} {formatDate(post.event_starts_at)}
                            </Text>
                          )}
                          {!!post.body && (
                            <Text className="text-[12.5px] leading-relaxed mb-3" style={{ color: "#d1d5db" }}>
                              {post.body}
                            </Text>
                          )}
                          {!!post.attachment_url && (
                            <Pressable
                              onPress={() => WebBrowser.openBrowserAsync(post.attachment_url!)}
                              className="flex-row items-center gap-1.5 px-3 py-2 rounded-full self-start"
                              style={{ backgroundColor: theme.accentSoft }}
                            >
                              <FileText size={12} color={theme.accent} />
                              <Text className="text-[11px] font-sans-semibold" style={{ color: theme.accent }}>
                                View attachment
                              </Text>
                              <ExternalLink size={10} color={theme.accent} />
                            </Pressable>
                          )}
                        </View>
                      )}
                    </Pressable>
                  );
                })
              )}
            </ScrollView>
          </Pressable>
        </Pressable>
      </Modal>
    </>
  );
}

// frontend/src/lib/components/NoticeBoard.svelte
<script>
  // Institution-only Notice Board — notices + official releases (exam
  // results, fee deadlines, circulars) for a site with vertical =
  // 'institution'. `posts` (current, not-yet-expired) and `pastPosts`
  // (expired — TimelineScreen splits on event_starts_at, an optional
  // "relevant until" date; see its filteredCurrentNotices/
  // filteredPastNotices) are both already scoped/sorted by the backend
  // (GET /api/campus/posts — pinned first, then newest; see
  // services/campusPosts.js's listActivePosts). Shown as its own full-width
  // banner section in the Campus feed (see TimelineScreen), not sharing a
  // grid cell with Quick Links, with an explicit "View all" call-to-action
  // and an urgent-count badge so a student's eye actually lands here first;
  // tapping it opens a modal with the full scrollable, interactive list,
  // with a Current/Past tab when there's anything to show on the Past side.
  // Uses the Campus tab's dark green/gold palette by default — `theme`
  // lets a different vertical (e.g. Community) reuse this component
  // wholesale with its own palette instead. Every call site that doesn't
  // pass `theme` renders pixel-identical to before this prop existed.
  import { onMount } from 'svelte';
  import { Pin, FileText, Megaphone, ExternalLink, ChevronDown, ChevronRight, Search, X } from '@lucide/svelte';

  const DEFAULT_THEME = {
    bg: '#0b1e13',
    bgAlt: '#0a1b11',
    border: '#12301e',
    borderAlt: '#163a23',
    borderHover: '#2a5c3a',
    accent: '#c29d53',
    accentSoft: 'rgba(194,157,83,0.18)',
    accentGradA: '#d4af6a',
    accentGradB: '#8b6a35',
    bannerGradA: '#123420',
    bannerGradB: '#0d2317',
    bannerBorder: '#1c472e',
    glow: 'rgba(212,175,106,0.22)'
  };

  let { posts = [], pastPosts = [], theme = DEFAULT_THEME } = $props();

  let modalOpen = $state(false);
  let expandedId = $state(null);
  let activeTab = $state('current'); // 'all' | 'current' | 'past'
  // 'all' concatenates rather than re-sorts — posts and pastPosts are each
  // already pinned-first/newest-first from the backend, so current notices
  // (the more actionable half) simply lead, with past ones trailing.
  const visiblePosts = $derived(
    activeTab === 'all' ? [...posts, ...pastPosts] : activeTab === 'current' ? posts : pastPosts
  );

  // Matches on title/category/body — same fields the top-level Campus
  // search and Exam Timetable's own search already match on, so filtering
  // behaves consistently everywhere in the Campus tab.
  let query = $state('');
  const filteredVisiblePosts = $derived.by(() => {
    const q = query.trim().toLowerCase();
    if (!q) return visiblePosts;
    return visiblePosts.filter((p) => [p.title, p.category, p.body].some((f) => (f || '').toLowerCase().includes(q)));
  });

  // static/pin.webp is a stock photo flattened onto a plain white square
  // (with a faint diagonal watermark baked into that white), not a real
  // cutout. A flat brightness threshold left watermark speckle behind and
  // risked eating the pin's own specular highlights (which are near-white
  // too). Flood-filling inward from the canvas border instead only erases
  // the region that's actually *connected* to the background — it walks
  // through the watermark fine (still near-white, low-saturation) but
  // stops at the pin's silhouette (dark metal needle / saturated yellow),
  // so highlights fully enclosed by the pin survive untouched.
  let pinSrc = $state('/pin.webp');
  onMount(() => {
    const img = new Image();
    img.src = '/pin.webp';
    img.onload = () => {
      const w = img.naturalWidth;
      const h = img.naturalHeight;
      const canvas = document.createElement('canvas');
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      const frame = ctx.getImageData(0, 0, w, h);
      const px = frame.data;
      const visited = new Uint8Array(w * h);
      const stack = [];
      for (let x = 0; x < w; x++) {
        stack.push(x, x + (h - 1) * w);
      }
      for (let y = 0; y < h; y++) {
        stack.push(y * w, y * w + (w - 1));
      }
      while (stack.length) {
        const i = stack.pop();
        if (visited[i]) continue;
        visited[i] = 1;
        const o = i * 4;
        const r = px[o], g = px[o + 1], b = px[o + 2];
        const brightness = (r + g + b) / 3;
        const saturation = Math.max(r, g, b) - Math.min(r, g, b);
        if (brightness < 165 || saturation > 60) continue;
        px[o + 3] = 0;
        const x = i % w;
        const y = (i - x) / w;
        if (x > 0) stack.push(i - 1);
        if (x < w - 1) stack.push(i + 1);
        if (y > 0) stack.push(i - w);
        if (y < h - 1) stack.push(i + w);
      }
      ctx.putImageData(frame, 0, 0);
      pinSrc = canvas.toDataURL('image/png');
    };
  });

  function toggle(id) {
    expandedId = expandedId === id ? null : id;
  }
  function openModal() {
    modalOpen = true;
    expandedId = null;
    query = '';
    // Land on whichever tab actually has something — e.g. a site with only
    // expired notices right now shouldn't open onto an empty Current list.
    activeTab = posts.length > 0 ? 'current' : 'past';
  }
  function closeModal() {
    modalOpen = false;
  }
  function handleKeydown(e) {
    if (e.key === 'Escape') closeModal();
  }

  const PRIORITY_COLOR = {
    urgent: '#C45C38',
    important: '#c29d53',
    normal: '#5b6b60'
  };
  const TYPE_LABEL = { notice: 'Notice', release: 'Release' };

  function formatDate(iso) {
    return new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  }

  // The top (pinned/newest) notice previews on the trigger card — posts is
  // already sorted pinned-first by the backend.
  const topPost = $derived(posts[0]);
  const urgentCount = $derived(posts.filter((p) => p.priority === 'urgent').length);
</script>

<svelte:window onkeydown={modalOpen ? handleKeydown : undefined} />

{#if posts.length > 0 || pastPosts.length > 0}
  <button
    type="button"
    onclick={openModal}
    class="notice-banner w-full text-left rounded-2xl overflow-hidden relative transition-all active:scale-[0.99]"
    style="background: linear-gradient(135deg, {theme.bannerGradA}, {theme.bannerGradB} 65%); border: 1px solid {theme.bannerBorder}; box-shadow: 0 10px 30px rgba(0,0,0,0.35); --nb-border-hover: {theme.borderHover};"
  >
    <!-- Soft accent glow in the corner rather than a literal pin illustration
         dominating the card — reads as a dashboard banner, not a bulletin
         board photo, while the pin graphic itself moves into the icon tile
         below (still the flood-fill cutout built in onMount; see script). -->
    <div class="absolute inset-0 pointer-events-none" style="background: radial-gradient(circle at 88% -20%, {theme.glow}, transparent 60%);"></div>
    <div class="relative flex items-center gap-3.5 px-5 py-4">
      <div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" style="background: linear-gradient(135deg, {theme.accentGradA}, {theme.accentGradB});">
        <img
          src={pinSrc}
          alt=""
          aria-hidden="true"
          style="width: 20px; height: auto; filter: drop-shadow(0 2px 3px rgba(0,0,0,0.4));"
        />
      </div>
      <div class="min-w-0 flex-1">
        <div class="flex items-center gap-2 flex-wrap mb-1">
          <p class="text-xs font-bold uppercase tracking-wider" style="color: {theme.accent};">Notice Board</p>
          {#if urgentCount > 0}
            <span class="text-[9px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded-full" style="background: rgba(196,92,56,0.22); color: #E08A6A;">
              {urgentCount} urgent
            </span>
          {/if}
        </div>
        {#if posts.length > 0}
          <p class="text-sm font-semibold leading-snug truncate" style="color: #f3f4f6;">{topPost?.title}</p>
        {:else}
          <p class="text-sm font-semibold leading-snug truncate" style="color: #9ca3af;">No current notices</p>
        {/if}
      </div>
      <div class="flex flex-col items-end gap-1.5 shrink-0">
        <span class="text-[10px] font-bold px-2.5 py-1.5 rounded-full flex items-center gap-1" style="background: {theme.accentSoft}; color: {theme.accent};">
          View all <ChevronRight size={11} />
        </span>
        {#if posts.length > 0}
          <span class="text-[10px]" style="color: #6b7280;">{posts.length} notice{posts.length === 1 ? '' : 's'}</span>
        {:else}
          <span class="text-[10px]" style="color: #6b7280;">{pastPosts.length} past</span>
        {/if}
      </div>
    </div>
  </button>
{/if}

{#if modalOpen}
  <div
    class="fixed inset-0 z-[100] flex items-end sm:items-center justify-center"
    style="background: rgba(0,0,0,0.65);"
    onclick={closeModal}
    role="presentation"
  >
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="modal-pop w-full sm:max-w-md rounded-t-3xl sm:rounded-3xl shadow-2xl flex flex-col"
      style="background: {theme.bg}; max-height: 85vh; border: 1px solid {theme.border};"
      onclick={(e) => e.stopPropagation()}
    >
      <div class="flex items-center justify-between px-5 pt-5 pb-3 shrink-0" style="border-bottom: 1px solid rgba(255,255,255,0.08);">
        <div>
          <p class="text-[10px] font-bold uppercase tracking-[0.2em]" style="color: {theme.accent};">Notice Board</p>
          <p class="text-[11px] mt-0.5" style="color: #9ca3af;">{filteredVisiblePosts.length} of {visiblePosts.length} notices</p>
        </div>
        <button
          onclick={closeModal}
          aria-label="Close"
          class="w-8 h-8 rounded-full flex items-center justify-center shrink-0"
          style="background: rgba(255,255,255,0.08);"
        >
          <X size={14} color="#9ca3af" />
        </button>
      </div>

      <!-- Always visible (not just once a notice has actually expired) so
           the filter is a discoverable, standing part of the modal rather
           than something that only appears once Past has content. -->
      <div class="flex gap-2 px-5 pt-3 shrink-0">
        <button
          onclick={() => (activeTab = 'all')}
          class="px-3 py-1.5 rounded-full text-[11px] font-bold transition-colors"
          style={activeTab === 'all'
            ? `background: ${theme.accent}; color: ${theme.bg};`
            : `background: ${theme.bgAlt}; border: 1px solid ${theme.borderAlt}; color: #9ca3af;`}
        >
          All ({posts.length + pastPosts.length})
        </button>
        <button
          onclick={() => (activeTab = 'current')}
          class="px-3 py-1.5 rounded-full text-[11px] font-bold transition-colors"
          style={activeTab === 'current'
            ? `background: ${theme.accent}; color: ${theme.bg};`
            : `background: ${theme.bgAlt}; border: 1px solid ${theme.borderAlt}; color: #9ca3af;`}
        >
          Current ({posts.length})
        </button>
        <button
          onclick={() => (activeTab = 'past')}
          class="px-3 py-1.5 rounded-full text-[11px] font-bold transition-colors"
          style={activeTab === 'past'
            ? `background: ${theme.accent}; color: ${theme.bg};`
            : `background: ${theme.bgAlt}; border: 1px solid ${theme.borderAlt}; color: #9ca3af;`}
        >
          Past ({pastPosts.length})
        </button>
      </div>

      <div class="px-5 pt-3 pb-3 shrink-0">
        <div class="flex items-center gap-2 rounded-lg px-3.5 py-2.5 search-box" style="background: {theme.bgAlt}; border: 1px solid {theme.borderAlt}; --nb-accent: {theme.accent};">
          <Search size={14} color={theme.accent} class="shrink-0" />
          <input
            bind:value={query}
            type="text"
            placeholder="Search notices…"
            class="flex-1 min-w-0 bg-transparent text-sm outline-none placeholder-[#6b7280]"
            style="color: #e5e7eb;"
          />
          {#if query}
            <button onclick={() => (query = '')} aria-label="Clear search" class="shrink-0">
              <X size={13} color="#9ca3af" />
            </button>
          {/if}
        </div>
      </div>

      <div class="px-5 pb-4 overflow-y-auto flex flex-col gap-2.5">
        {#if filteredVisiblePosts.length === 0}
          <p class="text-sm text-center py-8" style="color: #9ca3af;">
            {query ? `No notices match "${query}".` : activeTab === 'all' ? 'No notices yet.' : `No ${activeTab} notices.`}
          </p>
        {:else}
        {#each filteredVisiblePosts as post (post.id)}
          {@const color = PRIORITY_COLOR[post.priority] ?? PRIORITY_COLOR.normal}
          {@const open = expandedId === post.id}
          <button
            type="button"
            onclick={() => toggle(post.id)}
            class="text-left rounded-xl overflow-hidden transition-transform active:scale-[0.99]"
            style="background: rgba(255,255,255,0.04); border-left: 3px solid {color};"
          >
            <div class="flex items-start gap-3 px-4 py-3.5">
              <div class="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5" style="background: {color}30;">
                <Megaphone size={14} color={color} />
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-1.5 flex-wrap mb-1">
                  <span class="text-[9px] font-bold uppercase tracking-[0.12em] px-1.5 py-0.5 rounded" style="background: {color}25; color: {color};">
                    {TYPE_LABEL[post.type] ?? post.type}
                  </span>
                  {#if post.category}
                    <span class="text-[10px]" style="color: #9ca3af;">{post.category}</span>
                  {/if}
                  {#if post.is_pinned}<Pin size={10} color={theme.accent} fill={theme.accent} />{/if}
                </div>
                <p class="text-sm font-semibold leading-snug" style="color: #f3f4f6;">{post.title}</p>
                {#if !open}
                  <p class="text-[11px] mt-0.5 line-clamp-1" style="color: #6b7280;">{post.body ?? ''}</p>
                {/if}
              </div>
              <div class="flex flex-col items-end gap-1 shrink-0">
                <span class="text-[10px]" style="color: #6b7280;">{formatDate(post.published_at)}</span>
                <ChevronDown size={13} color="#6b7280" style="transition: transform 0.2s; transform: rotate({open ? 180 : 0}deg);" />
              </div>
            </div>

            {#if open}
              <div class="px-4 pb-4" style="padding-left: 3.25rem;">
                {#if post.event_starts_at}
                  <!-- Judged per-post rather than off activeTab — on the
                       All tab, current and past notices sit side by side. -->
                  <p class="text-[11px] mb-2" style="color: #9ca3af;">
                    {new Date(post.event_starts_at) < new Date() ? 'Expired' : 'Relevant until'} {formatDate(post.event_starts_at)}
                  </p>
                {/if}
                {#if post.body}
                  <p class="text-[12.5px] leading-relaxed mb-3" style="color: #d1d5db;">{post.body}</p>
                {/if}
                {#if post.attachment_url}
                  <a
                    href={post.attachment_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    onclick={(e) => e.stopPropagation()}
                    class="inline-flex items-center gap-1.5 text-[11px] font-semibold px-3 py-2 rounded-full"
                    style="background: {theme.accentSoft}; color: {theme.accent};"
                  >
                    <FileText size={12} /> View attachment <ExternalLink size={10} />
                  </a>
                {/if}
              </div>
            {/if}
          </button>
        {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}

<style>
  .notice-banner:hover {
    border-color: var(--nb-border-hover, #2a5c3a) !important;
  }
  .search-box:focus-within {
    border-color: var(--nb-accent, #c29d53) !important;
  }
  .modal-pop {
    animation: notice-modal-in 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);
  }
  @keyframes notice-modal-in {
    from {
      opacity: 0;
      transform: translateY(16px) scale(0.98);
    }
    to {
      opacity: 1;
      transform: translateY(0) scale(1);
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .modal-pop {
      animation: none;
    }
  }
</style>
