// mobile_app/src/components/PastEvents.tsx
// Ported from frontend/src/lib/components/PastEvents.svelte.
import { useState } from "react";
import { View, Text, Pressable, Modal, TextInput, ScrollView, Image } from "react-native";
import { X, ChevronLeft, ChevronRight, MapPin, CalendarDays, Images, Search } from "lucide-react-native";

export type PastEventPost = {
  id: number | string;
  title: string;
  category?: string | null;
  location?: string | null;
  body?: string | null;
  is_pinned?: boolean;
  attachment_url?: string | null;
  images?: string[];
  event_starts_at: string;
};

const DEFAULT_THEME = { bg: "#0b1e13", border: "#12301e", accent: "#c29d53", placeholderIcon: "#3a5240", carouselBg: "#05140b" };
const VISIBLE_LIMIT = 6;

function dayNum(iso: string) {
  return new Date(iso).getDate();
}
function monthAbbrev(iso: string) {
  return new Date(iso).toLocaleDateString(undefined, { month: "short" });
}
function fullDate(iso: string) {
  return new Date(iso).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" });
}

function EventCard({ post, theme }: { post: PastEventPost; theme: typeof DEFAULT_THEME; onPress: () => void }) {
  const galleryCount = (post.images?.length ?? 0) + (post.attachment_url ? 1 : 0);
  return (
    <View className="rounded-2xl overflow-hidden relative" style={{ height: 128, borderWidth: post.is_pinned ? 2 : 0, borderColor: theme.accent }}>
      {post.attachment_url ? (
        <Image source={{ uri: post.attachment_url }} style={{ width: "100%", height: "100%" }} resizeMode="cover" />
      ) : (
        <View className="w-full h-full items-center justify-center" style={{ backgroundColor: theme.border }}>
          <CalendarDays size={22} color={theme.placeholderIcon} />
        </View>
      )}
      <View className="absolute inset-0" style={{ backgroundColor: "rgba(0,0,0,0.35)" }} />
      <View className="absolute top-2.5 left-2.5 px-2 py-1 rounded-lg" style={{ backgroundColor: "rgba(0,0,0,0.55)" }}>
        <Text className="text-[9px] font-sans-semibold uppercase" style={{ color: theme.accent }}>
          {monthAbbrev(post.event_starts_at)} {dayNum(post.event_starts_at)}
        </Text>
      </View>
      {galleryCount > 1 && (
        <View className="absolute top-2.5 right-2.5 flex-row items-center gap-0.5 px-1.5 py-1 rounded-lg" style={{ backgroundColor: "rgba(0,0,0,0.55)" }}>
          <Images size={9} color="#fff" />
          <Text className="text-[9px] font-sans-semibold text-white">{galleryCount}</Text>
        </View>
      )}
      <View className="absolute bottom-0 left-0 right-0 p-2.5">
        {!!post.location && (
          <View className="flex-row items-center gap-1 mb-0.5">
            <MapPin size={8} color="#C4DAC0" />
            <Text className="text-[9px] font-sans-semibold" numberOfLines={1} style={{ color: "#C4DAC0" }}>
              {post.location}
            </Text>
          </View>
        )}
        <Text className="text-xs font-sans-semibold text-white leading-tight" numberOfLines={2}>
          {post.title}
        </Text>
      </View>
    </View>
  );
}

export default function PastEvents({ posts = [], theme = DEFAULT_THEME }: { posts?: PastEventPost[]; theme?: typeof DEFAULT_THEME }) {
  const overflow = Math.max(posts.length - (VISIBLE_LIMIT - 1), 0);
  const stripPosts = overflow > 0 ? posts.slice(0, VISIBLE_LIMIT - 1) : posts;

  const [modalOpen, setModalOpen] = useState(false);
  const [query, setQuery] = useState("");
  const q = query.trim().toLowerCase();
  const filtered = !q ? posts : posts.filter((p) => [p.title, p.category, p.location, p.body].some((f) => (f || "").toLowerCase().includes(q)));

  const [selected, setSelected] = useState<PastEventPost | null>(null);
  const [photoIndex, setPhotoIndex] = useState(0);
  const photos = selected ? [selected.attachment_url, ...(selected.images ?? [])].filter(Boolean) as string[] : [];

  function open(post: PastEventPost) {
    setSelected(post);
    setPhotoIndex(0);
  }

  if (posts.length === 0) return null;

  return (
    <>
      <View className="pt-2 pb-2">
        <View className="flex-row items-center justify-between px-4 mb-3">
          <Text className="text-sm font-sans-semibold" style={{ color: "#f3f4f6" }}>
            Past Events
          </Text>
        </View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: 16, gap: 12 }}>
          {stripPosts.map((post) => (
            <Pressable key={post.id} onPress={() => open(post)} style={{ width: 158 }}>
              <EventCard post={post} theme={theme} onPress={() => open(post)} />
            </Pressable>
          ))}
          {overflow > 0 && (
            <Pressable
              onPress={() => setModalOpen(true)}
              className="rounded-2xl items-center justify-center"
              style={{ width: 158, height: 128, backgroundColor: theme.bg, borderWidth: 1, borderStyle: "dashed", borderColor: theme.border, gap: 6 }}
            >
              <CalendarDays size={18} color={theme.accent} />
              <Text className="text-xs font-sans-semibold" style={{ color: "#e5e7eb" }}>
                +{overflow} more
              </Text>
            </Pressable>
          )}
        </ScrollView>
      </View>

      <Modal visible={modalOpen} animationType="slide" transparent onRequestClose={() => setModalOpen(false)}>
        <Pressable className="flex-1 justify-end" style={{ backgroundColor: "rgba(0,0,0,0.65)" }} onPress={() => setModalOpen(false)}>
          <Pressable style={{ backgroundColor: theme.bg, maxHeight: "85%", borderTopLeftRadius: 24, borderTopRightRadius: 24 }} onPress={(e) => e.stopPropagation()}>
            <View className="flex-row items-center justify-between px-5 pt-5 pb-3">
              <View>
                <Text className="text-[10px] font-sans-semibold uppercase tracking-[3px]" style={{ color: theme.accent }}>
                  Past Events
                </Text>
                <Text className="text-[11px] mt-0.5" style={{ color: "#9ca3af" }}>
                  {filtered.length} of {posts.length} events
                </Text>
              </View>
              <Pressable onPress={() => setModalOpen(false)} className="w-8 h-8 rounded-full items-center justify-center" style={{ backgroundColor: "rgba(255,255,255,0.08)" }}>
                <X size={14} color="#9ca3af" />
              </Pressable>
            </View>
            <View className="px-5 pb-3">
              <View className="flex-row items-center gap-2 rounded-lg px-3.5 py-2.5" style={{ backgroundColor: theme.bg, borderWidth: 1, borderColor: theme.border }}>
                <Search size={14} color={theme.accent} />
                <TextInput value={query} onChangeText={setQuery} placeholder="Search past events…" placeholderTextColor="#6b7280" className="flex-1 text-sm" style={{ color: "#e5e7eb" }} />
                {!!query && (
                  <Pressable onPress={() => setQuery("")}>
                    <X size={13} color="#9ca3af" />
                  </Pressable>
                )}
              </View>
            </View>
            <ScrollView contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 24, flexDirection: "row", flexWrap: "wrap", gap: 12, justifyContent: "space-between" }}>
              {filtered.length === 0 ? (
                <Text className="text-sm text-center py-8 w-full" style={{ color: "#9ca3af" }}>
                  {query ? `No events match "${query}".` : "Nothing here yet."}
                </Text>
              ) : (
                filtered.map((post) => (
                  <Pressable
                    key={post.id}
                    onPress={() => {
                      setModalOpen(false);
                      open(post);
                    }}
                    style={{ width: "47%" }}
                  >
                    <EventCard post={post} theme={theme} onPress={() => open(post)} />
                  </Pressable>
                ))
              )}
            </ScrollView>
          </Pressable>
        </Pressable>
      </Modal>

      <Modal visible={!!selected} animationType="slide" transparent onRequestClose={() => setSelected(null)}>
        <Pressable className="flex-1 justify-end" style={{ backgroundColor: "rgba(0,0,0,0.75)" }} onPress={() => setSelected(null)}>
          <Pressable style={{ backgroundColor: theme.bg, maxHeight: "90%", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden" }} onPress={(e) => e.stopPropagation()}>
            {selected && (
              <>
                <View className="relative" style={{ aspectRatio: 4 / 3, backgroundColor: theme.carouselBg }}>
                  {photos.length > 0 ? (
                    <>
                      <Image source={{ uri: photos[photoIndex] }} style={{ width: "100%", height: "100%" }} resizeMode="cover" />
                      {photos.length > 1 && (
                        <>
                          <Pressable
                            onPress={() => setPhotoIndex((i) => (i - 1 + photos.length) % photos.length)}
                            className="absolute left-2 top-1/2 w-8 h-8 rounded-full items-center justify-center"
                            style={{ backgroundColor: "rgba(0,0,0,0.5)", marginTop: -16 }}
                          >
                            <ChevronLeft size={16} color="#fff" />
                          </Pressable>
                          <Pressable
                            onPress={() => setPhotoIndex((i) => (i + 1) % photos.length)}
                            className="absolute right-2 top-1/2 w-8 h-8 rounded-full items-center justify-center"
                            style={{ backgroundColor: "rgba(0,0,0,0.5)", marginTop: -16 }}
                          >
                            <ChevronRight size={16} color="#fff" />
                          </Pressable>
                          <View className="absolute bottom-3 left-0 right-0 flex-row items-center justify-center gap-1.5">
                            {photos.map((_, i) => (
                              <View key={i} style={{ width: i === photoIndex ? 14 : 5, height: 5, borderRadius: 3, backgroundColor: i === photoIndex ? theme.accent : "rgba(255,255,255,0.4)" }} />
                            ))}
                          </View>
                        </>
                      )}
                    </>
                  ) : (
                    <View className="w-full h-full items-center justify-center">
                      <CalendarDays size={32} color={theme.placeholderIcon} />
                    </View>
                  )}
                  <Pressable onPress={() => setSelected(null)} className="absolute top-3 right-3 w-8 h-8 rounded-full items-center justify-center" style={{ backgroundColor: "rgba(0,0,0,0.55)" }}>
                    <X size={14} color="#fff" />
                  </Pressable>
                </View>
                <ScrollView className="px-5 py-4" style={{ gap: 8 }}>
                  <Text className="text-[10px] font-sans-semibold uppercase tracking-[3px]" style={{ color: theme.accent }}>
                    {fullDate(selected.event_starts_at)}
                  </Text>
                  <Text className="text-lg font-serif leading-snug mt-1" style={{ color: "#f3f4f6" }}>
                    {selected.title}
                  </Text>
                  {!!selected.location && (
                    <View className="flex-row items-center gap-1.5 mt-1.5">
                      <MapPin size={12} color="#9ca3af" />
                      <Text className="text-xs" style={{ color: "#9ca3af" }}>
                        {selected.location}
                      </Text>
                    </View>
                  )}
                  {!!selected.body && (
                    <Text className="text-[12.5px] leading-relaxed mt-2" style={{ color: "#d1d5db" }}>
                      {selected.body}
                    </Text>
                  )}
                </ScrollView>
              </>
            )}
          </Pressable>
        </Pressable>
      </Modal>
    </>
  );
}

// frontend/src/lib/components/PastEvents.svelte
<script>
  // Institution-only Past Events — campus_posts rows of type='event' whose
  // date has already passed (TimelineScreen splits campus_posts into
  // upcoming, shown in CampusEventsStrip, vs past, shown here — see its
  // filteredPastEvents/filteredUpcomingEvents). Deliberately mirrors the
  // Watch tab's "News & Stories" strip (horizontal photo cards, most-recent
  // first) rather than Campus's other trigger-card+modal components, since
  // this is a browsable memory/highlights feed, not a single actionable
  // item. Tapping a card opens a detail sheet with a photo carousel —
  // attachment_url is the cover photo (also the card's own background);
  // images (jsonb array, set in the admin Campus post form) holds any
  // additional gallery photos. Past VISIBLE_LIMIT events, the strip caps
  // itself and a trailing "+N more" card opens a searchable modal grid with
  // everything — same scale pattern as QuickLinksBoard/MarketplaceBoard.
  import { X, ChevronLeft, ChevronRight, MapPin, CalendarDays, Images, Search } from '@lucide/svelte';

  // Theme defaults to today's look — a different vertical (e.g. Community)
  // can pass its own palette; every call site that omits `theme` renders
  // exactly as before this prop existed.
  const DEFAULT_THEME = {
    bg: '#0b1e13',
    border: '#12301e',
    accent: '#c29d53',
    placeholderIcon: '#3a5240',
    carouselBg: '#05140b'
  };

  let { posts = [], theme = DEFAULT_THEME } = $props();

  const VISIBLE_LIMIT = 6;
  const overflow = $derived(Math.max(posts.length - (VISIBLE_LIMIT - 1), 0));
  const stripPosts = $derived(overflow > 0 ? posts.slice(0, VISIBLE_LIMIT - 1) : posts);

  let modalOpen = $state(false);
  let query = $state('');
  const filtered = $derived.by(() => {
    const q = query.trim().toLowerCase();
    if (!q) return posts;
    return posts.filter((p) => [p.title, p.category, p.location, p.body].some((f) => (f || '').toLowerCase().includes(q)));
  });

  let selected = $state(null);
  let photoIndex = $state(0);

  function open(post) {
    selected = post;
    photoIndex = 0;
  }
  function close() {
    selected = null;
  }
  function openModal() {
    modalOpen = true;
    query = '';
  }
  function closeModal() {
    modalOpen = false;
  }
  function handleKeydown(e) {
    if (e.key !== 'Escape') return;
    if (selected) close();
    else if (modalOpen) closeModal();
  }

  function dayNum(iso) {
    return new Date(iso).getDate();
  }
  function monthAbbrev(iso) {
    return new Date(iso).toLocaleDateString(undefined, { month: 'short' });
  }
  function fullDate(iso) {
    return new Date(iso).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' });
  }

  // Cover photo first, then the gallery — a post with no photos at all
  // still opens fine (the carousel area just shows a placeholder icon).
  const photos = $derived(
    selected ? [selected.attachment_url, ...(selected.images ?? [])].filter(Boolean) : []
  );
  function nextPhoto() {
    photoIndex = (photoIndex + 1) % photos.length;
  }
  function prevPhoto() {
    photoIndex = (photoIndex - 1 + photos.length) % photos.length;
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#snippet eventCard(post)}
  {@const galleryCount = (post.images?.length ?? 0) + (post.attachment_url ? 1 : 0)}
  <button
    type="button"
    onclick={() => open(post)}
    class="past-event-card w-full rounded-2xl overflow-hidden relative text-left active:scale-95 transition-transform"
    style="height: 128px; {post.is_pinned ? `border: 2px solid ${theme.accent};` : ''}"
  >
    {#if post.attachment_url}
      <img src={post.attachment_url} alt="" class="w-full h-full object-cover" />
    {:else}
      <div class="w-full h-full flex items-center justify-center" style="background: linear-gradient(135deg, {theme.border}, {theme.bg});">
        <CalendarDays size={22} color={theme.placeholderIcon} />
      </div>
    {/if}
    <div class="absolute inset-0" style="background: linear-gradient(0deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.1) 55%, transparent 100%);"></div>

    <div class="absolute top-2.5 left-2.5 px-2 py-1 rounded-lg text-[9px] font-bold uppercase tracking-wide" style="background: rgba(0,0,0,0.55); color: {theme.accent};">
      {monthAbbrev(post.event_starts_at)} {dayNum(post.event_starts_at)}
    </div>
    {#if galleryCount > 1}
      <div class="absolute top-2.5 right-2.5 flex items-center gap-0.5 px-1.5 py-1 rounded-lg" style="background: rgba(0,0,0,0.55);">
        <Images size={9} color="#fff" />
        <span class="text-[9px] font-bold text-white">{galleryCount}</span>
      </div>
    {/if}

    <div class="absolute bottom-0 left-0 right-0 p-2.5">
      {#if post.location}
        <p class="text-[9px] font-semibold mb-0.5 flex items-center gap-1" style="color: #C4DAC0;">
          <MapPin size={8} class="shrink-0" />
          <span class="truncate">{post.location}</span>
        </p>
      {/if}
      <p class="text-xs font-bold text-white leading-tight line-clamp-2">{post.title}</p>
    </div>
  </button>
{/snippet}

{#if posts.length > 0}
  <div class="pt-2 pb-2">
    <div class="flex items-center justify-between px-4 mb-3">
      <h3 class="text-sm font-bold" style="color: #f3f4f6;">Past Events</h3>
    </div>
    <div class="flex gap-3 px-4 overflow-x-auto pb-2 no-scrollbar">
      {#each stripPosts as post (post.id)}
        <div class="shrink-0" style="width: 158px;">
          {@render eventCard(post)}
        </div>
      {/each}
      {#if overflow > 0}
        <button
          type="button"
          onclick={openModal}
          class="more-tile shrink-0 rounded-2xl flex flex-col items-center justify-center gap-1.5 text-center transition-all"
          style="width: 158px; height: 128px; background: {theme.bg}; border: 1px dashed {theme.border}; --pe-hover: {theme.accent};"
        >
          <CalendarDays size={18} color={theme.accent} />
          <p class="text-xs font-bold" style="color: #e5e7eb;">+{overflow} more</p>
        </button>
      {/if}
    </div>
  </div>
{/if}

{#if modalOpen}
  <div
    class="fixed inset-0 z-[100] flex items-end sm:items-center justify-center"
    style="background: rgba(0,0,0,0.65);"
    onclick={closeModal}
    role="presentation"
  >
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="modal-pop w-full sm:max-w-md rounded-t-3xl sm:rounded-3xl shadow-2xl flex flex-col"
      style="background: {theme.bg}; max-height: 85vh; border: 1px solid {theme.border};"
      onclick={(e) => e.stopPropagation()}
    >
      <div class="flex items-center justify-between px-5 pt-5 pb-3 shrink-0">
        <div>
          <p class="text-[10px] font-bold uppercase tracking-[0.2em]" style="color: {theme.accent};">Past Events</p>
          <p class="text-[11px] mt-0.5" style="color: #9ca3af;">{filtered.length} of {posts.length} events</p>
        </div>
        <button
          onclick={closeModal}
          aria-label="Close"
          class="w-8 h-8 rounded-full flex items-center justify-center shrink-0"
          style="background: rgba(255,255,255,0.08);"
        >
          <X size={14} color="#9ca3af" />
        </button>
      </div>

      <div class="px-5 pb-3 shrink-0">
        <div class="flex items-center gap-2 rounded-lg px-3.5 py-2.5 search-box" style="background: {theme.bg}; border: 1px solid {theme.border}; --pe-hover: {theme.accent};">
          <Search size={14} color={theme.accent} class="shrink-0" />
          <input
            bind:value={query}
            type="text"
            placeholder="Search past events…"
            class="flex-1 min-w-0 bg-transparent text-sm outline-none placeholder-[#6b7280]"
            style="color: #e5e7eb;"
          />
          {#if query}
            <button onclick={() => (query = '')} aria-label="Clear search" class="shrink-0">
              <X size={13} color="#9ca3af" />
            </button>
          {/if}
        </div>
      </div>

      <div class="px-5 pb-6 overflow-y-auto grid grid-cols-2 gap-3">
        {#if filtered.length === 0}
          <p class="col-span-2 text-sm text-center py-8" style="color: #9ca3af;">
            {query ? `No events match "${query}".` : 'Nothing here yet.'}
          </p>
        {:else}
          {#each filtered as post (post.id)}
            {@render eventCard(post)}
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}

{#if selected}
  <div
    class="fixed inset-0 z-[100] flex items-end sm:items-center justify-center"
    style="background: rgba(0,0,0,0.75);"
    onclick={close}
    role="presentation"
  >
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="modal-pop w-full sm:max-w-md rounded-t-3xl sm:rounded-3xl shadow-2xl flex flex-col overflow-hidden"
      style="background: {theme.bg}; max-height: 90vh; border: 1px solid {theme.border};"
      onclick={(e) => e.stopPropagation()}
    >
      <!-- Photo carousel -->
      <div class="relative shrink-0" style="aspect-ratio: 4 / 3; background: {theme.carouselBg};">
        {#if photos.length > 0}
          {#key photoIndex}
            <img src={photos[photoIndex]} alt="" class="carousel-photo w-full h-full object-cover" />
          {/key}
          {#if photos.length > 1}
            <button
              onclick={prevPhoto}
              aria-label="Previous photo"
              class="absolute left-2 top-1/2 -translate-y-1/2 w-8 h-8 rounded-full flex items-center justify-center"
              style="background: rgba(0,0,0,0.5);"
            >
              <ChevronLeft size={16} color="#fff" />
            </button>
            <button
              onclick={nextPhoto}
              aria-label="Next photo"
              class="absolute right-2 top-1/2 -translate-y-1/2 w-8 h-8 rounded-full flex items-center justify-center"
              style="background: rgba(0,0,0,0.5);"
            >
              <ChevronRight size={16} color="#fff" />
            </button>
            <div class="absolute bottom-3 left-0 right-0 flex items-center justify-center gap-1.5">
              {#each photos as _, i (i)}
                <span
                  class="rounded-full transition-all"
                  style="width: {i === photoIndex ? '14px' : '5px'}; height: 5px; background: {i === photoIndex ? theme.accent : 'rgba(255,255,255,0.4)'};"
                ></span>
              {/each}
            </div>
          {/if}
        {:else}
          <div class="w-full h-full flex items-center justify-center">
            <CalendarDays size={32} color={theme.placeholderIcon} />
          </div>
        {/if}
        <button
          onclick={close}
          aria-label="Close"
          class="absolute top-3 right-3 w-8 h-8 rounded-full flex items-center justify-center"
          style="background: rgba(0,0,0,0.55);"
        >
          <X size={14} color="#fff" />
        </button>
      </div>

      <div class="px-5 py-4 overflow-y-auto flex flex-col gap-2">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em]" style="color: {theme.accent};">{fullDate(selected.event_starts_at)}</p>
        <h3 class="text-lg font-bold leading-snug" style="color: #f3f4f6; font-family: 'Playfair Display', serif;">{selected.title}</h3>
        {#if selected.location}
          <div class="flex items-center gap-1.5 text-[12px]" style="color: #9ca3af;">
            <MapPin size={12} color="#9ca3af" />
            {selected.location}
          </div>
        {/if}
        {#if selected.body}
          <p class="text-[12.5px] leading-relaxed mt-1" style="color: #d1d5db;">{selected.body}</p>
        {/if}
      </div>
    </div>
  </div>
{/if}

<style>
  .past-event-card:active {
    filter: brightness(0.95);
  }
  .more-tile:hover,
  .search-box:focus-within {
    border-color: var(--pe-hover, #c29d53) !important;
  }
  .modal-pop {
    animation: past-event-modal-in 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);
  }
  .carousel-photo {
    animation: past-event-photo-fade 0.2s ease-out;
  }
  @keyframes past-event-modal-in {
    from {
      opacity: 0;
      transform: translateY(16px) scale(0.98);
    }
    to {
      opacity: 1;
      transform: translateY(0) scale(1);
    }
  }
  @keyframes past-event-photo-fade {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }
</style>
