// frontend/src/lib/screens/ActiveScreen.svelte
<script>
  import { Wifi, Signal, Clock, Phone, RotateCcw, MessageCircle, Globe } from '@lucide/svelte';
  import UnganaLogoMark from '$lib/components/UnganaLogoMark.svelte';
  import DemoBadge from '$lib/components/DemoBadge.svelte';
  import { formatTime, formatCompactDuration, getWarningThreshold } from '$lib/data.js';

  // `initialRemaining` lets a restored session (page reload while still
  // connected) resume the countdown from the actual time left instead of
  // restarting the full duration — see +page.svelte's session-restore check.
  let { pkg, phone, mode = 'simulation', initialRemaining = null, onExpiring, onExtend } = $props();

  const total = pkg.demoSecs;
  const warningThreshold = getWarningThreshold(total);
  let remaining = $state(initialRemaining ?? total);
  let warned = false;
  let returnBanner = $state(false);
  const originalTitle = document.title;

  // Countdown
  $effect(() => {
    const t = setInterval(() => {
      const next = remaining - 1;
      if (next <= warningThreshold && !warned) {
        warned = true;
        setTimeout(onExpiring, 0);
      }
      remaining = next;
    }, 1000);
    return () => clearInterval(t);
  });

  // Page Visibility — update tab title when hidden, restore + banner on return
  $effect(() => {
    const stored = originalTitle;
    let titleInterval = null;

    function onVisibilityChange() {
      if (document.hidden) {
        titleInterval = setInterval(() => {
          const r = remaining;
          const ts = formatCompactDuration(r);
          document.title = r <= warningThreshold ? `⚠️ ${ts} left — Ungana WiFi` : `⏱ ${ts} remaining — Ungana`;
        }, 1000);
      } else {
        if (titleInterval) {
          clearInterval(titleInterval);
          titleInterval = null;
        }
        document.title = stored;
        returnBanner = true;
        setTimeout(() => (returnBanner = false), 4000);
      }
    }

    document.addEventListener('visibilitychange', onVisibilityChange);
    return () => {
      document.removeEventListener('visibilitychange', onVisibilityChange);
      if (titleInterval) clearInterval(titleInterval);
      document.title = stored;
    };
  });

  const pct = $derived(remaining / total);
  const radius = 54;
  const circ = 2 * Math.PI * radius;
  const minsLeft = $derived(Math.ceil(remaining / 60));

  const stats = [
    { icon: Signal, label: 'Signal', value: 'Strong' },
    { icon: Wifi, label: 'Speed', value: '4.2 Mbps' },
    { icon: Clock, label: 'Plan', value: pkg.label }
  ];
</script>

<div
  class="flex flex-col px-5 pb-8"
  style="min-height: 100dvh; background: linear-gradient(160deg, #1D3C2A 0%, #2E5A3E 100%); position: relative;"
>
  <!-- Welcome-back banner -->
  <div
    style="position: absolute; top: 16px; left: 50%; transform: translateX(-50%) translateY({returnBanner
      ? '0'
      : '-60px'}); transition: transform 0.35s cubic-bezier(0.34,1.56,0.64,1); z-index: 50; pointer-events: none;"
  >
    <div
      class="flex items-center gap-2 px-4 py-2 rounded-full shadow-lg"
      style="background: {remaining <= warningThreshold
        ? '#B85038'
        : '#2E5A3E'}; border: 1px solid rgba(255,255,255,0.15); white-space: nowrap;"
    >
      <div class="w-2 h-2 rounded-full animate-pulse" style="background: {remaining <= warningThreshold ? '#ffb0a0' : '#C45C38'};"></div>
      <span class="text-xs font-semibold text-[#E8D4B0]">
        {remaining <= warningThreshold ? '⚠️ Session expiring soon!' : `${minsLeft} min left in your session`}
      </span>
    </div>
  </div>

  <!-- Header -->
  <div class="flex items-center justify-between pt-5 pb-4">
    <div class="flex items-center gap-2">
      <UnganaLogoMark height={24} />
      <span class="text-sm font-bold text-[#E8D4B0]" style="font-family: 'Playfair Display', serif;">Ungana</span>
    </div>
    <div
      class="flex items-center gap-1.5 px-3 py-1.5 rounded-full"
      style="background: rgba(196,92,56,0.30); border: 1px solid rgba(196,92,56,0.3);"
    >
      <div class="w-2 h-2 rounded-full bg-[#C45C38] animate-pulse"></div>
      <span class="text-xs font-bold text-[#C45C38]">LIVE</span>
    </div>
  </div>

  <!-- Online banner -->
  <div class="rounded-3xl mb-5 overflow-hidden" style="background: rgba(196,92,56,0.08); border: 1px solid rgba(196,92,56,0.35);">
    <div class="px-5 py-4 flex items-center gap-4">
      <div class="w-12 h-12 rounded-2xl flex items-center justify-center shrink-0" style="background: rgba(196,92,56,0.30);">
        <Wifi size={24} color="#C45C38" />
      </div>
      <div>
        <p class="text-base font-bold text-[#E8D4B0]" style="font-family: 'Playfair Display', serif;">You're Online!</p>
        <p class="text-xs text-[#C4DAC0] mt-0.5">Session started · {pkg.label} plan</p>
      </div>
    </div>
  </div>

  <!-- Countdown ring -->
  <div class="flex flex-col items-center mb-5">
    <div class="relative flex items-center justify-center" style="width: 160px; height: 160px;">
      <svg width="160" height="160" style="transform: rotate(-90deg);">
        <circle cx="80" cy="80" r={radius} fill="none" stroke="rgba(255,255,255,0.18)" stroke-width="10" />
        <circle
          cx="80"
          cy="80"
          r={radius}
          fill="none"
          stroke={pct > 0.4 ? '#C45C38' : pct > 0.2 ? '#CC8830' : '#B85038'}
          stroke-width="10"
          stroke-linecap="round"
          stroke-dasharray={circ}
          stroke-dashoffset={circ * (1 - pct)}
          style="transition: stroke-dashoffset 0.9s linear, stroke 1s;"
        />
      </svg>
      <div class="absolute flex flex-col items-center">
        <span class="text-3xl font-bold text-[#E8D4B0]" style="font-family: 'Inter', sans-serif; letter-spacing: -1px;">
          {formatTime(remaining)}
        </span>
        <span class="text-[10px] text-[#C4DAC0] mt-0.5 uppercase tracking-wider">remaining</span>
      </div>
    </div>
    <p class="text-xs text-[#AECAAE] mt-2">{pkg.duration} total · expires when timer ends</p>
  </div>

  <!-- Stats row -->
  <div class="grid grid-cols-3 gap-2 mb-5">
    {#each stats as stat (stat.label)}
      {@const Icon = stat.icon}
      <div class="rounded-2xl flex flex-col items-center py-3 gap-1" style="background: rgba(255,255,255,0.14);">
        <Icon size={16} color="#C45C38" />
        <span class="text-[10px] text-[#AECAAE] uppercase tracking-wide">{stat.label}</span>
        <span class="text-xs font-bold text-[#E8D4B0]">{stat.value}</span>
      </div>
    {/each}
  </div>

  <!-- Account row -->
  <div
    class="rounded-2xl px-4 py-3 flex items-center gap-3 mb-5"
    style="background: rgba(255,255,255,0.12); border: 1px solid rgba(255,255,255,0.18);"
  >
    <div class="w-8 h-8 rounded-xl flex items-center justify-center" style="background: rgba(196,92,56,0.30);">
      <Phone size={14} color="#C45C38" />
    </div>
    <div class="flex-1">
      <p class="text-[10px] text-[#AECAAE] uppercase tracking-wider">Registered number</p>
      <p class="text-sm font-semibold text-[#E8D4B0]">+254 {phone}</p>
    </div>
  </div>

  <button
    onclick={() => window.open('https://www.google.com', '_blank', 'noopener,noreferrer')}
    class="w-full py-4 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 transition-all active:scale-95 mb-2"
    style="background: linear-gradient(135deg, #C45C38, #CC8830); color: #fff;"
  >
    <Globe size={16} />Go Online
  </button>
  <button
    onclick={onExtend}
    class="w-full py-3.5 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 active:scale-95 mb-2"
    style="background: rgba(255,255,255,0.14); color: #C4DAC0;"
  >
    <RotateCcw size={15} />Extend Session
  </button>
  <button
    class="w-full py-3.5 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 active:scale-95"
    style="background: rgba(255,255,255,0.14); color: #C4DAC0;"
  >
    <MessageCircle size={15} />Support
  </button>
  {#if mode !== 'active'}<DemoBadge />{/if}
</div>

// mobile_app/src/screens/ActiveScreen.tsx
// Ported from frontend/src/lib/screens/ActiveScreen.svelte. Two deliberate
// behavior drops, not oversights — see the plan doc's "MAC limitation"
// section:
//   - The "Go Online" button (window.open to release the captive portal)
//     has no native equivalent and is removed rather than reimplemented —
//     there's no captive-portal tab to release; the device's connection
//     already carries traffic once the router has authorized its real MAC.
//   - document.title tab-rewriting while hidden has no RN equivalent
//     (no background-tab concept) and is dropped; the "welcome back" banner
//     itself is kept, using RN's AppState to detect foreground return
//     instead of the Page Visibility API.
import { useEffect, useRef, useState } from "react";
import { View, Text, Pressable, Animated, AppState, type AppStateStatus } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import Svg, { Circle } from "react-native-svg";
import { Wifi, Phone, RotateCcw, MessageCircle, Megaphone, Zap, Users, ChevronRight } from "lucide-react-native";
import UnganaLogoMark from "@/components/UnganaLogoMark";
import DemoBadge from "@/components/DemoBadge";
import { formatTime, getWarningThreshold, type Package } from "@/lib/data";
import { getSite } from "@/lib/api";
import { getSiteId } from "@/lib/device";

const RADIUS = 54;
const CIRC = 2 * Math.PI * RADIUS;

export default function ActiveScreen({
  pkg,
  phone,
  mode = "simulation",
  initialRemaining = null,
  onExpiring,
  onExtend,
  onExplore,
}: {
  pkg: Package;
  phone: string;
  mode?: "simulation" | "active";
  initialRemaining?: number | null;
  // autoGoOnline is intentionally not a prop here — see the file header.
  onExpiring: () => void;
  onExtend: () => void;
  onExplore: () => void;
}) {
  const insets = useSafeAreaInsets();
  const site = getSiteId();
  const [siteVertical, setSiteVertical] = useState("general");
  const isInstitution = siteVertical === "institution";
  const isCommunity = siteVertical === "community";

  const total = pkg.demoSecs;
  const warningThreshold = getWarningThreshold(total);
  const [remaining, setRemaining] = useState(initialRemaining ?? total);
  const warned = useRef(false);
  const [returnBanner, setReturnBanner] = useState(false);
  const bannerTranslate = useRef(new Animated.Value(-60)).current;

  useEffect(() => {
    Animated.spring(bannerTranslate, { toValue: returnBanner ? 0 : -60, useNativeDriver: true, friction: 8 }).start();
  }, [returnBanner, bannerTranslate]);

  useEffect(() => {
    const t = setInterval(() => {
      setRemaining((prev) => {
        const next = prev - 1;
        if (next <= warningThreshold && !warned.current) {
          warned.current = true;
          setTimeout(onExpiring, 0);
        }
        return next;
      });
    }, 1000);
    return () => clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Foreground-return banner — the mobile equivalent of the source's Page
  // Visibility "welcome back" flash (the tab-title-rewriting half of that
  // effect has no native equivalent and isn't ported).
  useEffect(() => {
    function onChange(state: AppStateStatus) {
      if (state === "active") {
        setReturnBanner(true);
        setTimeout(() => setReturnBanner(false), 4000);
      }
    }
    const subscription = AppState.addEventListener("change", onChange);
    return () => subscription.remove();
  }, []);

  useEffect(() => {
    (async () => {
      if (site) {
        const result = await getSite(site);
        if (result.ok && result.data?.site) setSiteVertical(result.data.site.vertical ?? "general");
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const pct = remaining / total;
  const minsLeft = Math.ceil(remaining / 60);
  const ringColor = pct > 0.4 ? "#C45C38" : pct > 0.2 ? "#CC8830" : "#B85038";

  return (
    <LinearGradient colors={["#1D3C2A", "#2E5A3E"]} style={{ flex: 1 }}>
    <View className="flex-1 px-5" style={{ paddingTop: insets.top + 8, paddingBottom: insets.bottom + 24 }}>
      <Animated.View
        pointerEvents="none"
        style={{ position: "absolute", top: 16, left: "50%", marginLeft: -110, zIndex: 50, transform: [{ translateY: bannerTranslate }] }}
      >
        <View
          className="flex-row items-center gap-2 px-4 py-2 rounded-full"
          style={{ backgroundColor: remaining <= warningThreshold ? "#B85038" : "#2E5A3E", borderWidth: 1, borderColor: "rgba(255,255,255,0.15)", width: 220 }}
        >
          <View className="w-2 h-2 rounded-full" style={{ backgroundColor: remaining <= warningThreshold ? "#ffb0a0" : "#C45C38" }} />
          <Text className="text-xs font-sans-semibold" numberOfLines={1} style={{ color: "#E8D4B0" }}>
            {remaining <= warningThreshold ? "⚠️ Session expiring soon!" : `${minsLeft} min left in your session`}
          </Text>
        </View>
      </Animated.View>

      <View className="flex-row items-center justify-between pt-5 pb-4">
        <View className="flex-row items-center gap-2">
          <UnganaLogoMark height={24} />
          <Text className="text-sm font-serif" style={{ color: "#E8D4B0" }}>
            Ungana
          </Text>
        </View>
        <View className="flex-row items-center gap-1.5 px-3 py-1.5 rounded-full" style={{ backgroundColor: "rgba(196,92,56,0.30)", borderWidth: 1, borderColor: "rgba(196,92,56,0.3)" }}>
          <View className="w-2 h-2 rounded-full" style={{ backgroundColor: "#C45C38" }} />
          <Text className="text-xs font-sans-semibold" style={{ color: "#C45C38" }}>
            LIVE
          </Text>
        </View>
      </View>

      <View className="rounded-3xl mb-5 overflow-hidden" style={{ backgroundColor: "rgba(196,92,56,0.08)", borderWidth: 1, borderColor: "rgba(196,92,56,0.35)" }}>
        <View className="px-5 py-4 flex-row items-center gap-4">
          <View className="w-12 h-12 rounded-2xl items-center justify-center" style={{ backgroundColor: "rgba(196,92,56,0.30)" }}>
            <Wifi size={24} color="#C45C38" />
          </View>
          <View>
            <Text className="text-base font-serif" style={{ color: "#E8D4B0" }}>
              You're Online!
            </Text>
            <Text className="text-xs mt-0.5" style={{ color: "#C4DAC0" }}>
              Session started · {pkg.label} plan
            </Text>
          </View>
        </View>
      </View>

      <View className="items-center mb-5">
        <View className="items-center justify-center" style={{ width: 160, height: 160 }}>
          <Svg width={160} height={160} style={{ transform: [{ rotate: "-90deg" }] }}>
            <Circle cx={80} cy={80} r={RADIUS} fill="none" stroke="rgba(255,255,255,0.18)" strokeWidth={10} />
            <Circle
              cx={80}
              cy={80}
              r={RADIUS}
              fill="none"
              stroke={ringColor}
              strokeWidth={10}
              strokeLinecap="round"
              strokeDasharray={CIRC}
              strokeDashoffset={CIRC * (1 - Math.max(0, pct))}
            />
          </Svg>
          <View className="absolute items-center">
            <Text className="text-3xl font-sans-semibold" style={{ color: "#E8D4B0", letterSpacing: -1 }}>
              {formatTime(Math.max(0, remaining))}
            </Text>
            <Text className="text-[10px] mt-0.5 uppercase tracking-wider" style={{ color: "#C4DAC0" }}>
              remaining
            </Text>
          </View>
        </View>
        <Text className="text-xs mt-2" style={{ color: "#AECAAE" }}>
          {pkg.duration} total · expires when timer ends
        </Text>
      </View>

      <Pressable onPress={onExplore} className="w-full rounded-2xl p-4 flex-row items-center gap-3 mb-5" style={{ backgroundColor: "rgba(196,92,56,0.10)", borderWidth: 1, borderColor: "rgba(196,92,56,0.35)" }}>
        <View className="w-10 h-10 rounded-xl items-center justify-center" style={{ backgroundColor: "rgba(196,92,56,0.30)" }}>
          {isInstitution ? <Megaphone size={18} color="#C45C38" /> : isCommunity ? <Users size={18} color="#C45C38" /> : <Zap size={18} color="#C45C38" />}
        </View>
        <View className="flex-1 min-w-0">
          <Text className="text-sm font-sans-semibold" style={{ color: "#E8D4B0" }}>
            {isInstitution ? "Explore Campus" : isCommunity ? "Explore Community" : "Watch & Earn"}
          </Text>
          <Text className="text-xs mt-0.5" style={{ color: "#C4DAC0" }}>
            {isInstitution ? "Notices, exam timetable & more" : isCommunity ? "Announcements, marketplace & more" : "Earn extra time while you're connected"}
          </Text>
        </View>
        <ChevronRight size={16} color="#C4DAC0" />
      </Pressable>

      <View className="rounded-2xl px-4 py-3 flex-row items-center gap-3 mb-5" style={{ backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)" }}>
        <View className="w-8 h-8 rounded-xl items-center justify-center" style={{ backgroundColor: "rgba(196,92,56,0.30)" }}>
          <Phone size={14} color="#C45C38" />
        </View>
        <View className="flex-1">
          <Text className="text-[10px] uppercase tracking-wider" style={{ color: "#AECAAE" }}>
            Registered number
          </Text>
          <Text className="text-sm font-sans-semibold" style={{ color: "#E8D4B0" }}>
            +254 {phone}
          </Text>
        </View>
      </View>

      <Pressable onPress={onExtend} className="w-full py-3.5 rounded-2xl flex-row items-center justify-center gap-2 mb-2" style={{ backgroundColor: "rgba(255,255,255,0.14)" }}>
        <RotateCcw size={15} color="#C4DAC0" />
        <Text className="text-sm font-sans-semibold" style={{ color: "#C4DAC0" }}>
          Extend Session
        </Text>
      </Pressable>
      <Pressable className="w-full py-3.5 rounded-2xl flex-row items-center justify-center gap-2" style={{ backgroundColor: "rgba(255,255,255,0.14)" }}>
        <MessageCircle size={15} color="#C4DAC0" />
        <Text className="text-sm font-sans-semibold" style={{ color: "#C4DAC0" }}>
          Support
        </Text>
      </Pressable>
      {mode !== "active" && <DemoBadge />}
    </View>
    </LinearGradient>
  );
}
