// frontend/src/lib/screens/EndedScreen.svelte
<script>
  import { WifiOff, RotateCcw, MessageCircle } from '@lucide/svelte';
  import ScreenBg from '$lib/components/ScreenBg.svelte';

  let { pkg, phone, onBuyAgain } = $props();

  const rows = $derived([
    { label: 'Plan used', value: `${pkg.label} · ${pkg.duration}` },
    { label: 'Number', value: `+254 ${phone}` },
    { label: 'Amount paid', value: `${pkg.price.toLocaleString()} KES` },
    { label: 'Status', value: 'Completed ✓' }
  ]);
</script>

<ScreenBg class="items-center">
  <!-- Icon -->
  <div class="flex flex-col items-center mt-8 mb-6">
    <div
      class="w-24 h-24 rounded-full flex items-center justify-center mb-4"
      style="background: rgba(46,90,62,0.12); border: 2px solid rgba(46,90,62,0.25);"
    >
      <WifiOff size={44} color="#3C6A4A" strokeWidth={1.5} />
    </div>
    <div class="px-3 py-1 rounded-full mb-3" style="background: rgba(46,90,62,0.12); border: 1px solid rgba(46,90,62,0.2);">
      <span class="text-xs font-bold text-[#3C6A4A] uppercase tracking-widest">Session Ended</span>
    </div>
    <h2 class="text-2xl font-bold text-[#1D3C2A] text-center" style="font-family: 'Playfair Display', serif;">Your time is up</h2>
    <p class="text-sm text-[#3C6A4A] mt-1.5 text-center">Your {pkg.label} session has ended</p>
  </div>

  <!-- Summary card -->
  <div class="w-full rounded-3xl overflow-hidden shadow-xl mb-4" style="background: #2E5A3E;">
    <div class="px-5 pt-5 pb-4">
      <p class="text-xs text-[#C4DAC0] uppercase tracking-widest mb-3 font-semibold">Session Summary</p>
      {#each rows as row (row.label)}
        <div class="flex justify-between items-center py-2.5 border-b border-white/10 last:border-0">
          <span class="text-xs text-[#C4DAC0]">{row.label}</span>
          <span class="text-sm font-semibold text-[#E8D4B0] text-right">{row.value}</span>
        </div>
      {/each}
    </div>
  </div>

  <!-- Prompt -->
  <div class="w-full rounded-2xl px-4 py-4 mb-5 text-center" style="background: rgba(46,90,62,0.1); border: 1px solid rgba(46,90,62,0.15);">
    <p class="text-sm font-semibold text-[#1D3C2A]">Would you like to buy another session?</p>
    <p class="text-xs text-[#3C6A4A] mt-1">Stay connected with a new plan</p>
  </div>

  <div class="cta-pulse-wrap w-full mb-3">
    <button
      onclick={onBuyAgain}
      class="w-full py-4 rounded-2xl font-bold text-base flex items-center justify-center gap-2 transition-transform active:scale-90"
      style="background: linear-gradient(135deg, #C45C38, #CC8830); color: #fff;"
    >
      <RotateCcw size={18} />Buy Another Session
    </button>
  </div>

  <button
    class="w-full py-3.5 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 active:scale-95 mb-2"
    style="background: #1D3C2A; color: #E8D4B0;"
  >
    <MessageCircle size={16} />Contact Support
  </button>

  <p class="text-[10px] text-[#7A8868] text-center mt-3">swap.ungana.app</p>
</ScreenBg>

<style>
  /* Draws the eye back to the main CTA: a slow breathing scale paired with
     an expanding, fading pulse ring — reads as "tap me" without being
     distracting or fighting the button's own tap-feedback scale (that
     lives on the button itself, not this wrapper). */
  .cta-pulse-wrap {
    position: relative;
    border-radius: 1rem;
    animation: cta-breathe 2.4s ease-in-out infinite;
  }
  .cta-pulse-wrap::after {
    content: '';
    position: absolute;
    inset: 0;
    border-radius: 1rem;
    box-shadow: 0 0 0 0 rgba(196, 92, 56, 0.45);
    animation: cta-ring 2.4s ease-out infinite;
    pointer-events: none;
  }
  @keyframes cta-breathe {
    0%,
    100% {
      transform: scale(1);
    }
    50% {
      transform: scale(1.035);
    }
  }
  @keyframes cta-ring {
    0% {
      box-shadow: 0 0 0 0 rgba(196, 92, 56, 0.45);
    }
    70% {
      box-shadow: 0 0 0 14px rgba(196, 92, 56, 0);
    }
    100% {
      box-shadow: 0 0 0 0 rgba(196, 92, 56, 0);
    }
  }
</style>

// mobile_app/src/screens/EndedScreen.tsx
// Ported from frontend/src/lib/screens/EndedScreen.svelte.
import { useEffect, useRef } from "react";
import { View, Text, Pressable, Animated } from "react-native";
import { WifiOff, RotateCcw, MessageCircle } from "lucide-react-native";
import ScreenBg from "@/components/ScreenBg";
import type { Package } from "@/lib/data";

export default function EndedScreen({
  pkg,
  phone,
  onBuyAgain,
}: {
  pkg: Package;
  phone: string;
  onBuyAgain: () => void;
}) {
  const rows = [
    { label: "Plan used", value: `${pkg.label} · ${pkg.duration}` },
    { label: "Number", value: `+254 ${phone}` },
    { label: "Amount paid", value: `${pkg.price.toLocaleString()} KES` },
    { label: "Status", value: "Completed ✓" },
  ];

  // Same "draw the eye back to the CTA" breathing-scale + expanding pulse
  // ring as the source's CSS keyframes, via RN's built-in Animated API (no
  // extra dependency needed for one looping effect).
  const scale = useRef(new Animated.Value(1)).current;
  const ringScale = useRef(new Animated.Value(1)).current;
  const ringOpacity = useRef(new Animated.Value(0.45)).current;

  useEffect(() => {
    const breathe = Animated.loop(
      Animated.sequence([
        Animated.timing(scale, { toValue: 1.035, duration: 1200, useNativeDriver: true }),
        Animated.timing(scale, { toValue: 1, duration: 1200, useNativeDriver: true }),
      ])
    );
    const ring = Animated.loop(
      Animated.sequence([
        Animated.timing(ringScale, { toValue: 1, duration: 0, useNativeDriver: true }),
        Animated.timing(ringOpacity, { toValue: 0.45, duration: 0, useNativeDriver: true }),
        Animated.parallel([
          Animated.timing(ringScale, { toValue: 1.25, duration: 2400, useNativeDriver: true }),
          Animated.timing(ringOpacity, { toValue: 0, duration: 2400, useNativeDriver: true }),
        ]),
      ])
    );
    breathe.start();
    ring.start();
    return () => {
      breathe.stop();
      ring.stop();
    };
  }, [scale, ringScale, ringOpacity]);

  return (
    <ScreenBg className="items-center">
      <View className="items-center mt-8 mb-6">
        <View
          className="w-24 h-24 rounded-full items-center justify-center mb-4"
          style={{ backgroundColor: "rgba(46,90,62,0.12)", borderWidth: 2, borderColor: "rgba(46,90,62,0.25)" }}
        >
          <WifiOff size={44} color="#3C6A4A" strokeWidth={1.5} />
        </View>
        <View className="px-3 py-1 rounded-full mb-3" style={{ backgroundColor: "rgba(46,90,62,0.12)", borderWidth: 1, borderColor: "rgba(46,90,62,0.2)" }}>
          <Text className="text-xs font-sans-semibold uppercase tracking-widest" style={{ color: "#3C6A4A", letterSpacing: 1.5 }}>
            Session Ended
          </Text>
        </View>
        <Text className="text-2xl font-serif text-center" style={{ color: "#1D3C2A" }}>
          Your time is up
        </Text>
        <Text className="text-sm mt-1.5 text-center" style={{ color: "#3C6A4A" }}>
          Your {pkg.label} session has ended
        </Text>
      </View>

      <View className="w-full mb-2" style={{ position: "relative" }}>
        <Animated.View
          pointerEvents="none"
          style={{
            position: "absolute",
            inset: 0,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: "rgba(196,92,56,0.45)",
            opacity: ringOpacity,
            transform: [{ scale: ringScale }],
          }}
        />
        <Animated.View style={{ transform: [{ scale }] }}>
          <Pressable
            onPress={onBuyAgain}
            className="w-full py-4 rounded-2xl flex-row items-center justify-center gap-2 active:opacity-90"
            style={{ backgroundColor: "#C45C38" }}
          >
            <RotateCcw size={18} color="#fff" />
            <Text className="text-base font-sans-semibold text-white">Buy Another Session</Text>
          </Pressable>
        </Animated.View>
      </View>
      <Text className="text-xs text-center mb-5" style={{ color: "#3C6A4A" }}>
        Stay connected with a new plan
      </Text>

      <View className="w-full rounded-3xl overflow-hidden mb-4" style={{ backgroundColor: "#2E5A3E" }}>
        <View className="px-5 pt-5 pb-4">
          <Text className="text-xs uppercase tracking-widest mb-3 font-sans-semibold" style={{ color: "#C4DAC0" }}>
            Session Summary
          </Text>
          {rows.map((row, i) => (
            <View
              key={row.label}
              className="flex-row justify-between items-center py-2.5"
              style={i < rows.length - 1 ? { borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.1)" } : undefined}
            >
              <Text className="text-xs" style={{ color: "#C4DAC0" }}>
                {row.label}
              </Text>
              <Text className="text-sm font-sans-semibold text-right" style={{ color: "#E8D4B0" }}>
                {row.value}
              </Text>
            </View>
          ))}
        </View>
      </View>

      <Pressable className="w-full py-3.5 rounded-2xl flex-row items-center justify-center gap-2 mb-2" style={{ backgroundColor: "#1D3C2A" }}>
        <MessageCircle size={16} color="#E8D4B0" />
        <Text className="text-sm font-sans-semibold" style={{ color: "#E8D4B0" }}>
          Contact Support
        </Text>
      </Pressable>

      <Text className="text-[10px] text-center mt-3" style={{ color: "#7A8868" }}>
        swap.ungana.app
      </Text>
    </ScreenBg>
  );
}
